import test from 'node:test';
import assert from 'node:assert/strict';
import { AIStoryPlanner, OpenAICompatibleProvider } from '../src/runtime/modules/ai-provider.js';
import { Planner } from '../src/runtime/modules/planner.js';
import { Composer } from '../src/runtime/modules/composer.js';
const source='# Growth\n\n## Context\nRevenue grew 18%.\n\n## Plan\nImprove onboarding and sales follow-up.';
function planOf(count,target=count){return {schemaVersion:1,purpose:'Explain growth plan',audience:'Leadership',tone:'clear',targetSlides:target,storyArc:['context','evidence','action'],sections:[{id:'s1',title:'Growth'}],slideIntents:Array.from({length:count},(_,index)=>index===0?{goal:'Open',roleHint:'cover',title:'Growth',topic:'Growth',facts:[],takeaway:'',emphasis:'title'}:{goal:`Slide ${index+1}`,roleHint:index===1?'metrics':'statement',title:`Topic ${index+1}`,topic:`Topic ${index+1}`,facts:[`Metric ${100+index}`],takeaway:'Continue',emphasis:'balanced'})}}
const validPlan=planOf(3);
class MockProvider{constructor(values){this.values=[...values];this.calls=0;this.requests=[]}async generateStructured(request){this.calls++;this.requests.push(request);const value=this.values.shift();if(value instanceof Error)throw value;return {text:value}}}
test('AI planner accepts valid structured response and compiles through DeckSpec',async()=>{const provider=new MockProvider([JSON.stringify(validPlan)]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:3});assert.equal(result.mode,'ai');assert.equal(result.attempts,1);assert.equal(result.plan.targetSlides,3);assert.equal(result.plan.actualSlides,3);assert.equal(Planner.validateDeckPlan(result.plan).ok,true);const spec=Planner.toDeckSpec(result.plan);assert.equal(Composer.validateDeckSpec(spec).ok,true);assert.ok(Composer.compileDeck(spec,{seed:'ai-mock'}).project)});
test('AI planner retries malformed JSON then succeeds',async()=>{const provider=new MockProvider(['{bad json',JSON.stringify(validPlan)]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:3,attempts:2});assert.equal(result.mode,'ai');assert.equal(result.attempts,2);assert.equal(provider.calls,2);assert.ok(result.warnings.some(w=>w.code==='AI_JSON_PARSE'))});
test('AI planner treats roleHint as advisory and normalizes through DeckSpec',async()=>{const advisory={...validPlan,slideIntents:[{...validPlan.slideIntents[0],roleHint:'title-slide'},{...validPlan.slideIntents[1],roleHint:'kpi-dashboard'},...validPlan.slideIntents.slice(2)]},provider=new MockProvider([JSON.stringify(advisory)]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:3,attempts:2});assert.equal(result.mode,'ai');assert.equal(result.attempts,1);assert.equal(Planner.validateDeckPlan(result.plan).ok,true);const spec=Planner.toDeckSpec(result.plan);assert.equal(Composer.validateDeckSpec(spec).ok,true);assert.notEqual(spec.slides[0].role,'kpi-dashboard');assert.ok(Composer.compileDeck(spec,{seed:'ai-role-hint'}).project)});
test('provider failure and timeout-like errors do not expose keys and fall back',async()=>{const err=Object.assign(new Error('network down'),{code:'AI_PROVIDER_FAILURE'}),result=await AIStoryPlanner.plan(source,{provider:new MockProvider([err,err]),targetSlides:3});assert.equal(result.mode,'fallback');const provider=new OpenAICompatibleProvider({baseUrl:'http://localhost:1234/v1',apiKey:'secret-value',model:'local-model',fetch:async()=>{throw Object.assign(new Error('aborted'),{name:'AbortError'})}});assert.equal(provider.describe().apiKey,'[configured]');await assert.rejects(()=>provider.generateStructured({system:'x',user:'y'}),e=>e.code==='AI_TIMEOUT')});

test('AI page-count contract accepts exact requested count',async()=>{const provider=new MockProvider([JSON.stringify(planOf(10))]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:10,attempts:2});assert.equal(result.mode,'ai');assert.equal(result.plan.slideIntents.length,10);assert.equal(result.plan.targetSlides,10);assert.equal(provider.calls,1)});
test('AI page-count mismatch is repaired on bounded retry',async()=>{const provider=new MockProvider([JSON.stringify(planOf(2,10)),JSON.stringify(planOf(10,10))]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:10,attempts:2});assert.equal(result.mode,'ai');assert.equal(result.attempts,2);assert.equal(provider.calls,2);assert.ok(result.warnings.some(item=>item.code==='AI_PAGE_COUNT_MISMATCH'&&item.requested===10&&item.actual===2));const repair=JSON.parse(provider.requests[1].user).repair;assert.equal(repair.reason,'AI_PAGE_COUNT_MISMATCH');assert.equal(repair.requested,10);assert.equal(repair.actual,2)});
test('AI repeated page-count mismatch falls back deterministically and never reports mode=ai',async()=>{const provider=new MockProvider([JSON.stringify(planOf(2,10)),JSON.stringify(planOf(2,10))]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:10,attempts:2});assert.equal(result.mode,'fallback');assert.equal(result.fallbackMode,'deterministic');assert.equal(result.fallbackReason,'AI_PAGE_COUNT_MISMATCH');assert.equal(result.plan.targetSlides,10);assert.equal(provider.calls,2)});
test('AI zero-slide and over-count responses cannot succeed as mode=ai',async()=>{for(const count of [0,11]){const provider=new MockProvider([JSON.stringify(planOf(count,10)),JSON.stringify(planOf(count,10))]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:10,attempts:2});assert.equal(result.mode,'fallback',`${count} slides must fall back`);assert.notEqual(result.mode,'ai');assert.equal(result.plan.targetSlides,10)}});
