import test from 'node:test';
import assert from 'node:assert/strict';
import { AIStoryPlanner, OpenAICompatibleProvider } from '../src/runtime/modules/ai-provider.js';
import { Planner } from '../src/runtime/modules/planner.js';
import { Composer } from '../src/runtime/modules/composer.js';
const source='# Growth\n\n## Context\nRevenue grew 18%.\n\n## Plan\nImprove onboarding and sales follow-up.';
const validPlan={schemaVersion:1,purpose:'Explain growth plan',audience:'Leadership',tone:'clear',targetSlides:3,storyArc:['context','evidence','action'],sections:[{id:'s1',title:'Growth'}],slideIntents:[{goal:'Open',roleHint:'cover',title:'Growth',topic:'Growth',facts:[],takeaway:'',emphasis:'title'},{goal:'Evidence',roleHint:'metrics',title:'Revenue',topic:'Revenue',facts:['Revenue grew 18%'],takeaway:'Growth is strong',emphasis:'data'},{goal:'Action',roleHint:'process',title:'Next actions',topic:'Plan',facts:['Improve onboarding','Automate follow-up'],takeaway:'Execute consistently',emphasis:'balanced'}]};
class MockProvider{constructor(values){this.values=[...values];this.calls=0}async generateStructured(){this.calls++;const value=this.values.shift();if(value instanceof Error)throw value;return {text:value}}}
test('AI planner accepts valid structured response and compiles through DeckSpec',async()=>{const provider=new MockProvider([JSON.stringify(validPlan)]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:3});assert.equal(result.mode,'ai');assert.equal(result.attempts,1);assert.equal(Planner.validateDeckPlan(result.plan).ok,true);const spec=Planner.toDeckSpec(result.plan);assert.equal(Composer.validateDeckSpec(spec).ok,true);assert.ok(Composer.compileDeck(spec,{seed:'ai-mock'}).project)});
test('AI planner retries malformed JSON then succeeds',async()=>{const provider=new MockProvider(['{bad json',JSON.stringify(validPlan)]),result=await AIStoryPlanner.plan(source,{provider,targetSlides:3,attempts:2});assert.equal(result.mode,'ai');assert.equal(result.attempts,2);assert.equal(provider.calls,2);assert.ok(result.warnings.some(w=>w.code==='AI_JSON_PARSE'))});
test('AI planner rejects invalid roles and falls back deterministically',async()=>{const invalid={...validPlan,slideIntents:[{...validPlan.slideIntents[0],roleHint:'made-up-role'}]},provider=new MockProvider([JSON.stringify(invalid),JSON.stringify(invalid)]),a=await AIStoryPlanner.plan(source,{provider,targetSlides:3,attempts:2}),b=await AIStoryPlanner.plan(source,{provider:null,targetSlides:3});assert.equal(a.mode,'fallback');assert.deepEqual(a.plan,b.plan)});
test('provider failure and timeout-like errors do not expose keys and fall back',async()=>{const err=Object.assign(new Error('network down'),{code:'AI_PROVIDER_FAILURE'}),result=await AIStoryPlanner.plan(source,{provider:new MockProvider([err,err]),targetSlides:3});assert.equal(result.mode,'fallback');const provider=new OpenAICompatibleProvider({baseUrl:'http://localhost:1234/v1',apiKey:'secret-value',model:'local-model',fetch:async()=>{throw Object.assign(new Error('aborted'),{name:'AbortError'})}});assert.equal(provider.describe().apiKey,'[configured]');await assert.rejects(()=>provider.generateStructured({system:'x',user:'y'}),e=>e.code==='AI_TIMEOUT')});
