import test from 'node:test';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
import { PptxExporter } from '../src/runtime/modules/pptx-exporter.js';
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2v0sAAAAASUVORK5CYII=';
function project(){return {schemaVersion:1,id:'root',title:'PPTX Golden',text:'',mapLayout:'balanced',uiTheme:'light',presentationOrder:[],master:{bgColor:'#ffffff',bgImage:png,bgFit:'cover',elements:[]},children:[{id:'s1',title:'Editable objects',text:'',collapsed:false,pos:{x:0,y:0},children:[],slideElements:[{id:'t1',type:'text',x:80,y:70,w:800,h:80,z:1000,text:'Editable MindDeck Text',fontSize:36,fontWeight:700,color:'#172033'},{id:'sh1',type:'shape',shape:'roundRect',x:80,y:180,w:280,h:100,z:1001,fill:'#eef2ff',borderColor:'#5b6cff',borderWidth:2},{id:'im1',type:'image',x:400,y:180,w:100,h:100,z:1002,src:png,fit:'cover'},{id:'tb1',type:'table',x:80,y:320,w:650,h:260,z:1003,columns:[{width:1},{width:1}],header:{visible:true,cells:[{text:'Metric'},{text:'Value'}]},rows:[{cells:[{text:'Revenue'},{text:'+18%'}]},{cells:[{text:'Users'},{text:'1200'}]}],style:{fontSize:18,borderColor:'#d9deea',borderWidth:1}},{id:'ch1',type:'chart',x:780,y:180,w:700,h:320,z:1004,chartType:'bar',categories:['A','B','C'],series:[{name:'Series 1',values:[10,20,30]}],options:{showLegend:false,showValues:true}},{id:'dg1',type:'diagram',x:780,y:540,w:700,h:260,z:1005,subtype:'roadmap',data:{items:[{label:'Discover'},{label:'Build'},{label:'Launch'}]},style:{nodeFill:'#ffffff',nodeBorder:'#5b6cff',nodeText:'#172033',fontSize:18,borderWidth:1}}]}],slideElements:[{id:'cover',type:'text',x:120,y:200,w:1300,h:180,z:1000,text:'PPTX Golden',fontSize:64,fontWeight:800,color:'#172033'}],collapsed:false,pos:{x:0,y:0}}}
test('PPTX exporter emits valid editable OOXML package from MindDeck Project',async()=>{const result=await PptxExporter.exportProject(project(),{outputType:'arraybuffer'});assert.equal(result.slides,2);const bytes=new Uint8Array(result.data);assert.equal(bytes[0],0x50);assert.equal(bytes[1],0x4b);const zip=await JSZip.loadAsync(result.data),names=Object.keys(zip.files);assert.ok(names.includes('ppt/presentation.xml'));assert.ok(names.includes('ppt/slides/slide1.xml'));assert.ok(names.includes('ppt/slides/slide2.xml'));const slide1=await zip.file('ppt/slides/slide1.xml').async('string'),slide2=await zip.file('ppt/slides/slide2.xml').async('string');assert.match(slide2,/Editable MindDeck Text/);assert.match(slide2,/Revenue/);assert.ok(names.some(n=>n.startsWith('ppt/charts/chart')));assert.ok(names.some(n=>n.startsWith('ppt/media/')));const rels1=await zip.file('ppt/slides/_rels/slide1.xml.rels').async('string'),rels2=await zip.file('ppt/slides/_rels/slide2.xml.rels').async('string');assert.match(rels1,/image/,'master bgImage must be exported as a slide image relationship');assert.match(rels2,/image/);assert.match(slide1,/<p:pic/,'master bgImage must create a picture in OOXML');assert.match(slide2,/roundRect|prstGeom/);assert.match(slide2,/<a:srcRect/,'cover image fit should be represented as OOXML crop geometry')});

class FakeSlide{constructor(){this.images=[];this.shapes=[];this.text=[];this.tables=[];this.charts=[];this.background=null}addImage(value){this.images.push(value)}addShape(type,value){this.shapes.push({type,...value})}addText(text,value){this.text.push({text,...value})}addTable(rows,value){this.tables.push({rows,...value})}addChart(type,series,value){this.charts.push({type,series,...value})}}
class FakePptx{constructor(){this.slides=[];this.ShapeType={rect:'rect',roundRect:'roundRect',ellipse:'ellipse',line:'line'};this.ChartType={bar:'bar',line:'line',area:'area',doughnut:'doughnut'}}defineLayout(){}addSlide(){const slide=new FakeSlide();this.slides.push(slide);return slide}async write(){FakePptx.last=this;return new ArrayBuffer(8)}async writeFile(){FakePptx.last=this}}
test('PPTX exporter maps bgImage, fit/crop and diagram geometry deterministically',async()=>{const p={schemaVersion:1,id:'root',title:'Geometry',mapLayout:'balanced',uiTheme:'light',presentationOrder:[],master:{bgColor:'#fff',bgImage:png,bgFit:'contain',elements:[]},children:[{id:'s1',title:'Geometry',collapsed:false,pos:{x:0,y:0},children:[],slideElements:[{id:'crop',type:'image',x:120,y:120,w:480,h:240,z:1000,src:png,crop:{x:24,y:12,w:240,h:120}},{id:'matrix',type:'diagram',x:700,y:150,w:720,h:600,z:1001,subtype:'matrix',data:{items:Array.from({length:5},(_,i)=>({label:`N${i+1}`}))},layout:{columns:2,gap:20},style:{}}]}],slideElements:[],collapsed:false,pos:{x:0,y:0}};await PptxExporter.exportProject(p,{PptxGenJS:FakePptx,outputType:'arraybuffer'});const pptx=FakePptx.last,slide=pptx.slides[1];assert.equal(slide.images[0].sizing.type,'contain');assert.equal(slide.images[0].sizing.w,1600/120);assert.equal(slide.images[0].sizing.h,900/120);assert.equal(slide.images[1].sizing.type,'crop');assert.deepEqual(slide.images[1].sizing,{type:'crop',x:24/120,y:12/120,w:240/120,h:120/120});const nodes=slide.shapes.filter(item=>item.type==='roundRect');assert.equal(nodes.length,5);const xs=[...new Set(nodes.map(item=>item.x.toFixed(4)))],ys=[...new Set(nodes.map(item=>item.y.toFixed(4)))];assert.equal(xs.length,2,'matrix with layout.columns=2 must use exactly two columns');assert.equal(ys.length,3,'five matrix nodes in two columns must use three rows');for(const node of nodes){assert.ok(node.x>=700/120&&node.y>=150/120);assert.ok(node.x+node.w<=(700+720)/120+.001);assert.ok(node.y+node.h<=(150+600)/120+.001)}});
