import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Core } from '../src/core/runtime.js';
import { compileSlide, compileDeck, normalizeSlideContent, validateDeckSpec, Quality, ThemeRegistry } from '../src/core/composer.js';

function fakeDocument(){let doc;class Node{constructor(name){this.nodeName=name;this.children=[];this.attributes={};this.style={setProperty(){}};this.classList={add(){}};this.ownerDocument=doc;this.textContent=''}setAttribute(key,value){this.attributes[key]=String(value)}appendChild(node){this.children.push(node);return node}}doc={createElement:name=>new Node(name),createElementNS:(_ns,name)=>new Node(name)};return doc}
const tableData={columns:[{label:'能力',width:2,align:'left'},{label:'当前',width:1,align:'center'},{label:'目标',width:1,align:'right'}],header:{visible:true,height:54,cells:['能力','当前','目标']},rowHeights:[64,72],rows:[['Runtime','1','1'],{cells:['Portable','yes','yes']} ]};
const diagramItems=Array.from({length:5},(_,index)=>({label:`节点 ${index+1}`,detail:`说明 ${index+1}`}));
const diagramData=subtype=>({subtype,data:{centerLabel:'核心',items:diagramItems},layout:{columns:2,gap:20}});

await import('../src/runtime/shared-core.js?table-diagram-step4');
const GeneratedCore=globalThis.MindDeckCore;
for(const runtime of [Core,GeneratedCore]){
  assert.ok(runtime.NativeTable,'NativeTable must be exported by the shared runtime');
  assert.ok(runtime.NativeDiagram,'NativeDiagram must be exported by the shared runtime');
  assert.deepEqual(runtime.NativeDiagram.subtypes,['matrix','pyramid','cycle','funnel','roadmap','swot','pest','porter']);
  const tableCheck=runtime.NativeTable.validate(tableData);assert.equal(tableCheck.ok,true);assert.equal(tableCheck.normalized.columns[0].width,2);assert.equal(tableCheck.normalized.rows[0].height,64);assert.deepEqual(JSON.parse(JSON.stringify(tableCheck.normalized)),tableCheck.normalized);
  const tableHost=runtime.Element.create({id:'table-test',type:'table',x:100,y:180,w:900,h:500,z:1000,...tableData,style:{},animation:{type:'inherit',delay:0,duration:.5}},{document:fakeDocument(),animate:false});assert.ok(tableHost.children.some(child=>child.nodeName==='div'),'table must render through Element.create');
  for(const subtype of runtime.NativeDiagram.subtypes){const source=diagramData(subtype),check=runtime.NativeDiagram.validate(source);assert.equal(check.ok,true,`${subtype} schema must validate`);const normalized=runtime.NativeDiagram.normalize(source);assert.deepEqual(JSON.parse(JSON.stringify(normalized)),normalized,`${subtype} must stay JSON serializable`);const svg=runtime.NativeDiagram.render({id:`diagram-${subtype}`,type:'diagram',x:100,y:180,w:900,h:500,z:1000,...source,style:{}},{document:fakeDocument()});assert.equal(svg.nodeName,'svg');assert.ok(svg.children.length>0,`${subtype} must render native SVG primitives`);const host=runtime.Element.create({id:`diagram-host-${subtype}`,type:'diagram',x:100,y:180,w:900,h:500,z:1000,...source,style:{},animation:{type:'inherit',delay:0,duration:.5}},{document:fakeDocument(),animate:false});assert.ok(host.children.some(child=>child.nodeName==='svg'),`${subtype} must render through Element.create`)}
}

const cobalt=ThemeRegistry.resolve('cobalt'),sand=ThemeRegistry.resolve('sand'),cobaltTable=Core.NativeTable.themeStyle(cobalt),sandTable=Core.NativeTable.themeStyle(sand),cobaltDiagram=Core.NativeDiagram.themeStyle(cobalt),sandDiagram=Core.NativeDiagram.themeStyle(sand);
assert.equal(cobaltTable.variant,cobalt.tableStyle.variant);assert.equal(cobaltDiagram.variant,cobalt.diagramStyle.variant);assert.notEqual(cobaltTable.headerBackground,sandTable.headerBackground,'themes must visibly change table language');assert.notEqual(cobaltDiagram.nodeFill,sandDiagram.nodeFill,'themes must visibly change diagram language');assert.notEqual(cobaltDiagram.connectorWidth,sandDiagram.connectorWidth,'diagramStyle connector must be consumed');

const normalizedTableContent=normalizeSlideContent({title:'能力对照',table:tableData});assert.equal(normalizedTableContent.table.columns.length,3);
const normalizedDiagramContent=normalizeSlideContent({title:'SWOT',diagram:diagramData('swot')});assert.equal(normalizedDiagramContent.diagram.subtype,'swot');
const tableCompile=compileSlide({content:{title:'能力对照',table:tableData},template:'compare-table-01',theme:'cobalt'}),tableCompileAgain=compileSlide({content:{title:'能力对照',table:tableData},template:'compare-table-01',theme:'cobalt'});assert.deepEqual(tableCompileAgain.elements,tableCompile.elements,'table Composer output must be deterministic');assert.equal(tableCompile.elements.filter(element=>element.type==='table').length,1);
const diagramCompile=compileSlide({content:{title:'业务模型',diagram:diagramData('porter')},template:'cards-grid-01',theme:'cobalt'});assert.equal(diagramCompile.elements.filter(element=>element.type==='diagram').length,1);assert.equal(diagramCompile.elements.find(element=>element.type==='diagram').subtype,'porter');
const conflictSpec={schemaVersion:1,title:'冲突',goal:'验证',slides:[{id:'x',role:'compare',content:{title:'冲突',chart:{chartType:'bar',values:[1]},table:tableData}}]};assert.equal(validateDeckSpec(conflictSpec).ok,false,'chart/table/diagram body must be mutually exclusive');

const sample=JSON.parse(readFileSync(new URL('../examples/v10-table-diagram-golden/table-diagram.deck.json',import.meta.url),'utf8')),snapshot=JSON.parse(readFileSync(new URL('./golden/table-diagram.snapshot.json',import.meta.url),'utf8')),validation=validateDeckSpec(sample);assert.equal(validation.ok,true,validation.errors?.map(item=>item.message).join('; '));const compiled=compileDeck(sample,{theme:'cobalt'});assert.equal(compiled.quality.ok,true,compiled.quality.errors?.map(item=>item.code).join(','));const slides=(compiled.project.children||[]).map(node=>{const tables=node.slideElements.filter(element=>element.type==='table'),diagrams=node.slideElements.filter(element=>element.type==='diagram');return {id:node.id,role:node.composer?.role,tableCount:tables.length,diagramCount:diagrams.length,subtype:diagrams[0]?.subtype||null}});assert.deepEqual({schemaVersion:compiled.project.schemaVersion,theme:compiled.project.deckTheme,slides},snapshot.expected,'Step 4 table/diagram golden changed');assert.equal(Quality.validateProject(compiled.project).ok,true,'table/diagram-aware project quality must pass');

const saved=JSON.stringify(compiled.project),reloaded=JSON.parse(saved);Core.Project.normalize(reloaded);assert.equal(reloaded.children[0].slideElements.some(element=>element.type==='table'),true,'save/load must preserve table');assert.equal(reloaded.children[1].slideElements.some(element=>element.type==='diagram'),true,'save/load must preserve diagram');const portable=Core.ExportData.project(reloaded,'fusion');assert.equal(portable.children[0].slideElements.some(element=>element.type==='table'),true,'Portable must preserve table');assert.equal(portable.children[1].slideElements.some(element=>element.type==='diagram'),true,'Portable must preserve diagram');
const original=reloaded.children[0].slideElements.find(element=>element.type==='table'),copy=JSON.parse(JSON.stringify(original));copy.id='table-copy';copy.x+=24;copy.y+=20;copy.w+=40;copy.h+=10;Core.Project.normalizeElement(copy);assert.equal(copy.type,'table');assert.notEqual(copy.x,original.x);
const editorSource=readFileSync(new URL('../src/app/modules/20-slide-editor.js',import.meta.url),'utf8');assert.match(editorSource,/function duplicateSelected\(\)/,'editor must keep generic copy');assert.match(editorSource,/const c=clone\(e\)/,'editor copy must stay data-model based');assert.match(editorSource,/el\.x=Math\.round\(st\.x\+dx\)/,'editor move must stay generic');assert.match(editorSource,/el\.w=Math\.round\(nw\)/,'editor resize must stay generic');
console.log('MindDeck V10 Step 4 table + diagram: OK (table, 8 diagram subtypes, Composer, Theme, Editor, Portable, deterministic golden)');
