import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { SourceDocument } from '../src/runtime/modules/source-document.js';
import { Planner } from '../src/runtime/modules/planner.js';
import { Composer } from '../src/runtime/modules/composer.js';
const golden=JSON.parse(fs.readFileSync(new URL('./golden/v10-planner.snapshot.json',import.meta.url),'utf8'));
function source(){return {sourceType:'json',title:'V10 Strategy',metadata:{audience:'Leadership'},sections:[{title:'Background',content:'The market is expanding and customer needs are changing.'},{title:'Problem',content:'Conversion remains below target and onboarding is fragmented.'},{title:'Metrics',content:'Revenue grew 18%. Active users reached 1200.'},{title:'Process',content:'First simplify onboarding. Then automate follow-up. Finally review outcomes.'}]}}
test('V10 SourceDocument/Planner golden is stable',()=>{const doc=SourceDocument.normalize(source()),plan=Planner.deterministicPlan(doc,{targetSlides:5}),summary={title:doc.title,targetSlides:plan.targetSlides,roles:plan.slideIntents.map(s=>s.roleHint),titles:plan.slideIntents.map(s=>s.title)};assert.deepEqual(summary,golden)});
test('V10 representative 15-page deck compiles with role/template diversity and finite geometry',()=>{const sections=[['Background','Market context and customer expectations.'],['Problem','Problem: conversion is below target.'],['Metrics','Metrics: revenue grew 18% and users reached 1200.'],['Process','Process: first discover, then build, finally launch.'],['Compare','Compare current approach versus target model.'],['Timeline','Timeline and milestones for Q1 Q2 Q3 Q4.'],['Solution','Solution: simplify workflow and automate follow-up.'],['Architecture','Architecture: platform, service, data and security layers.'],['Roadmap','Roadmap: foundation, expansion, scale.'],['Case','Case study: pilot customer improved adoption.'],['Table','Table details: owner, metric, target.'],['Trend','Trend: growth moved from 10% to 18% to 25%.'],['Conclusion','Conclusion and next steps.'],['Action','Next step: execute, measure and iterate.']].map(([title,content])=>({title,content}));const plan=Planner.deterministicPlan({sourceType:'json',title:'V10 Quality Deck',sections},{targetSlides:15}),spec=Planner.toDeckSpec(plan,{theme:'aurora'}),compiled=Composer.compileDeck(spec,{seed:'v10-quality'}),description=Composer.describe(compiled.project);assert.equal(plan.targetSlides,15);assert.equal(description.pages,15);assert.ok(Object.keys(description.roles).length>=5);assert.ok(Object.keys(description.families).length>=3);for(const node of [compiled.project,...compiled.project.children])for(const e of node.slideElements||[])for(const key of ['x','y','w','h','z'])assert.ok(Number.isFinite(Number(e[key])),`${node.id}/${e.id} invalid ${key}`)});
test('V10 parse + planner + compile 25-slide smoke performance stays bounded',()=>{const sections=Array.from({length:24},(_,i)=>({title:i%4===0?'Metrics':i%4===1?'Problem':i%4===2?'Process':'Solution',content:`Section ${i+1}. Metric ${100+i}%. First analyze, then act.`}));const started=performance.now(),doc=SourceDocument.normalize({sourceType:'json',title:'Performance Deck',sections}),plan=Planner.deterministicPlan(doc,{targetSlides:25}),spec=Planner.toDeckSpec(plan),compiled=Composer.compileDeck(spec,{seed:'v10-performance'}),elapsed=performance.now()-started;assert.equal(Composer.describe(compiled.project).pages,25);assert.ok(elapsed<10000,`25-slide pipeline took ${elapsed.toFixed(1)}ms`)});
