export const CHART_TYPES=Object.freeze(['bar','line','area','donut','radar','funnel','waterfall']);
const NativeChartTypeSet=new Set(CHART_TYPES);
const NATIVE_CHART_DEFAULT_SERIES_PALETTE=Object.freeze(['#5B6CFF','#00A8A8','#0E9F6E','#D1495B','#8A4FFF','#D5A84D']);
export const chartFinite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
export const chartClamp=(value,min,max)=>Math.min(max,Math.max(min,value));
export const chartClean=value=>value===undefined||value===null?'':String(value).trim();
const chartArray=value=>Array.isArray(value)?value:[];
function chartPlainObject(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.nodeType!==undefined)return false;const proto=Object.getPrototypeOf(value);return proto===Object.prototype||proto===null}
function chartJsonSafe(value,seen=new Set()){
  if(value===null||['string','boolean'].includes(typeof value))return true;
  if(typeof value==='number')return Number.isFinite(value);
  if(['undefined','function','symbol','bigint'].includes(typeof value))return false;
  if(typeof value!=='object'||value.nodeType!==undefined||seen.has(value))return false;
  seen.add(value);const children=Array.isArray(value)?value:Object.values(value),ok=children.every(child=>chartJsonSafe(child,seen));seen.delete(value);return ok;
}
function chartNormalizeNumberList(values,length=null){const out=chartArray(values).map(value=>chartFinite(value,0));if(length!==null){while(out.length<length)out.push(0);out.length=length}return out}
function chartNormalizeStringList(values){return chartArray(values).map(chartClean)}
function chartNormalizeOptions(input={}){const source=chartPlainObject(input)?input:{},emphasisIndex=Number.isInteger(Number(source.emphasisIndex))?Number(source.emphasisIndex):-1;return {showLegend:source.showLegend!==false,showLabels:source.showLabels!==false,showValues:source.showValues===true,showGrid:source.showGrid!==false,stacked:source.stacked===true,smooth:source.smooth!==false,orientation:source.orientation==='horizontal'?'horizontal':'vertical',innerRadius:chartClamp(chartFinite(source.innerRadius,.58),.18,.86),emphasisIndex,min:source.min===null||source.min===undefined?null:chartFinite(source.min,0),max:source.max===null||source.max===undefined?null:chartFinite(source.max,0),startAngle:chartFinite(source.startAngle,-90)}}
function chartNormalizeSeries(input=[],categoryCount=0){return chartArray(input).map((series,index)=>{const source=chartPlainObject(series)?series:{},values=chartNormalizeNumberList(source.values,categoryCount||null);return {id:chartClean(source.id)||`series-${index+1}`,name:chartClean(source.name)||`Series ${index+1}`,values}}).filter(series=>series.values.length)}
export function normalizeChartData(input={}){
  const source=chartPlainObject(input)?input:{},chartType=NativeChartTypeSet.has(source.chartType)?source.chartType:'bar';
  let categories=chartNormalizeStringList(source.categories),labels=chartNormalizeStringList(source.labels),values=chartNormalizeNumberList(source.values);
  if(!categories.length&&labels.length)categories=labels.slice();if(!labels.length&&categories.length)labels=categories.slice();
  let categoryCount=Math.max(categories.length,labels.length),series=chartNormalizeSeries(source.series,categoryCount);
  if(!categoryCount&&series.length){categoryCount=Math.max(...series.map(item=>item.values.length),0);categories=Array.from({length:categoryCount},(_,i)=>`Item ${i+1}`);labels=categories.slice();series=chartNormalizeSeries(source.series,categoryCount)}
  if(!series.length&&values.length){categoryCount=Math.max(categoryCount,values.length);if(!categories.length)categories=Array.from({length:categoryCount},(_,i)=>labels[i]||`Item ${i+1}`);if(!labels.length)labels=categories.slice();series=[{id:'series-1',name:chartClean(source.seriesName)||'Series 1',values:chartNormalizeNumberList(values,categoryCount)}]}
  if(!values.length&&series.length)values=series[0].values.slice();if(!labels.length&&categories.length)labels=categories.slice();if(!categories.length&&labels.length)categories=labels.slice();
  categoryCount=Math.max(categories.length,labels.length,series[0]?.values.length||0,values.length);while(categories.length<categoryCount)categories.push(labels[categories.length]||`Item ${categories.length+1}`);while(labels.length<categoryCount)labels.push(categories[labels.length]||`Item ${labels.length+1}`);if(series.length)series=series.map(item=>({...item,values:chartNormalizeNumberList(item.values,categoryCount)}));values=chartNormalizeNumberList(values,categoryCount);
  return {chartType,categories,series,labels,values,options:chartNormalizeOptions(source.options)};
}
export function validateChartData(input={}){
  const errors=[],warnings=[];if(!chartPlainObject(input)){errors.push({code:'CHART_DATA_TYPE',path:'chart',message:'chart must be a plain JSON object'});return {ok:false,errors,warnings}}
  if(!chartJsonSafe(input))errors.push({code:'CHART_DATA_NOT_JSON',path:'chart',message:'chart data must be finite JSON-only data'});if(input.chartType!==undefined&&!NativeChartTypeSet.has(input.chartType))errors.push({code:'CHART_TYPE_UNSUPPORTED',path:'chart.chartType',message:`unsupported chart type: ${input.chartType}`});
  const normalized=normalizeChartData(input),count=Math.max(normalized.categories.length,normalized.labels.length,normalized.values.length,normalized.series[0]?.values.length||0),hasValues=chartArray(input.values).length>0||chartArray(input.series).some(series=>chartArray(series?.values).length>0);if(!hasValues)errors.push({code:'CHART_DATA_EMPTY',path:'chart',message:'chart requires at least one value'});if(normalized.chartType==='radar'&&count>0&&count<3)errors.push({code:'CHART_RADAR_TOO_SMALL',path:'chart',message:'radar chart requires at least three axes'});if(['bar','line','area','radar'].includes(normalized.chartType)&&normalized.series.length===0&&count>0)errors.push({code:'CHART_SERIES_REQUIRED',path:'chart.series',message:`${normalized.chartType} chart requires series values`});if(['donut','funnel','waterfall'].includes(normalized.chartType)&&normalized.values.length===0&&count>0)errors.push({code:'CHART_VALUES_REQUIRED',path:'chart.values',message:`${normalized.chartType} chart requires values`});return {ok:errors.length===0,errors,warnings,normalized};
}
export function normalizeChartStyle(input={}){const source=chartPlainObject(input)?input:{},palette=chartArray(source.seriesPalette).map(chartClean).filter(Boolean);return {variant:chartClean(source.variant)||'clean',text:chartClean(source.text)||'#172033',grid:chartClean(source.grid)||'subtle',gridColor:chartClean(source.gridColor)||'#D9DEEA',seriesPalette:palette.length?palette:NATIVE_CHART_DEFAULT_SERIES_PALETTE.slice(),axis:chartClean(source.axis)||'#667085',background:chartClean(source.background)||'transparent',emphasis:chartClean(source.emphasis)||palette[0]||'#5B6CFF',fontFamily:chartClean(source.fontFamily)||'Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif',labels:chartClean(source.labels)||'compact'}}
export function resolveChartThemeStyle(theme={}){const source=chartPlainObject(theme)?theme:{},chart=chartPlainObject(source.chartStyle)?source.chartStyle:source,colors=chartPlainObject(source.colors)?source.colors:source;return normalizeChartStyle({...chart,text:chart.text??colors.text,gridColor:chart.gridColor??colors.line,seriesPalette:chart.seriesPalette??[colors.accent,colors.accent2,colors.success,colors.danger,colors.muted].filter(Boolean),axis:chart.axis??colors.muted,background:chart.background??'transparent',emphasis:chart.emphasis??colors.accent,fontFamily:chart.fontFamily??source.typography?.fontFamily})}
export function normalizeChartElement(element){if(!element||element.type!=='chart')return element;const normalized=normalizeChartData(element);element.chartType=normalized.chartType;element.categories=normalized.categories;element.series=normalized.series;element.labels=normalized.labels;element.values=normalized.values;element.options=normalized.options;element.style=normalizeChartStyle(element.style);return element}
export function validateChartElement(element){const errors=[];if(!element||element.type!=='chart')errors.push({code:'CHART_ELEMENT_TYPE',path:'element.type',message:'element.type must be chart'});const data=validateChartData(element||{});for(const error of data.errors)errors.push(error);for(const key of ['x','y','w','h','z'])if(!Number.isFinite(Number(element?.[key])))errors.push({code:'CHART_GEOMETRY_INVALID',path:`element.${key}`,message:`${key} must be finite`});return {ok:errors.length===0,errors,warnings:data.warnings||[]}}
