import { chartClamp, chartClean, chartFinite } from './chart-data.js';
const NATIVE_CHART_SVG_NS='http://www.w3.org/2000/svg';
export function chartSvgNode(doc,name,attrs={},text=null){const node=doc.createElementNS(NATIVE_CHART_SVG_NS,name);for(const [key,value] of Object.entries(attrs))if(value!==undefined&&value!==null)node.setAttribute(key,String(value));if(text!==null)node.textContent=String(text);return node}
export function chartAddText(doc,svg,text,x,y,style,attrs={}){if(text===undefined||text===null||text==='')return null;const node=chartSvgNode(doc,'text',{x,y,fill:style.text,'font-size':attrs.size||24,'font-family':style.fontFamily,'text-anchor':attrs.anchor||'middle','dominant-baseline':attrs.baseline||'middle',opacity:attrs.opacity??1},text);svg.appendChild(node);return node}
export function chartPaletteColor(style,index,emphasis=false){return emphasis?style.emphasis:style.seriesPalette[index%style.seriesPalette.length]}
function chartRangeOf(values,options={}){let min=Math.min(0,...values),max=Math.max(0,...values);if(options.min!==null)min=options.min;if(options.max!==null)max=options.max;if(min===max){if(max===0)max=1;else{min=Math.min(0,min*.9);max=max*1.1}}return {min,max,span:max-min}}
export function chartGrid(doc,svg,box,style,options,range){if(!options.showGrid||style.grid==='none')return;const count=5,opacity=style.grid==='subtle'?.45:.85;for(let i=0;i<=count;i++){const y=box.y+box.h*i/count;svg.appendChild(chartSvgNode(doc,'line',{x1:box.x,y1:y,x2:box.x+box.w,y2:y,stroke:style.gridColor,'stroke-width':1,opacity}));const value=range.max-range.span*i/count;chartAddText(doc,svg,Math.round(value*100)/100,box.x-14,y,style,{size:18,anchor:'end',opacity:.8})}}
export function chartLegend(doc,svg,series,style){if(!series.length)return;let x=90;series.slice(0,5).forEach((item,index)=>{svg.appendChild(chartSvgNode(doc,'circle',{cx:x,cy:28,r:7,fill:chartPaletteColor(style,index)}));const label=chartAddText(doc,svg,item.name,x+14,29,style,{size:18,anchor:'start',opacity:.86});x+=Math.max(110,(chartClean(item.name).length*11)+48);if(label)x=Math.min(x,900)})}
export function chartRenderBar(doc,svg,data,style,box){const all=data.series.flatMap(item=>item.values),range=chartRangeOf(all,data.options);chartGrid(doc,svg,box,style,data.options,range);const zeroY=box.y+box.h*(range.max/range.span);svg.appendChild(chartSvgNode(doc,'line',{x1:box.x,y1:zeroY,x2:box.x+box.w,y2:zeroY,stroke:style.axis,'stroke-width':1.5}));const groups=Math.max(1,data.categories.length),seriesCount=Math.max(1,data.series.length),groupW=box.w/groups*.72,step=box.w/groups,barW=data.options.stacked?groupW:groupW/seriesCount;data.categories.forEach((label,i)=>{let posBase=0,negBase=0;data.series.forEach((series,s)=>{const value=chartFinite(series.values[i]),start=data.options.stacked?(value>=0?posBase:negBase):0,end=start+value;if(data.options.stacked){if(value>=0)posBase=end;else negBase=end}const y1=box.y+box.h*(range.max-start)/range.span,y2=box.y+box.h*(range.max-end)/range.span,x=box.x+i*step+(step-groupW)/2+(data.options.stacked?0:s*barW),y=Math.min(y1,y2),h=Math.max(1,Math.abs(y2-y1)),emphasis=i===data.options.emphasisIndex;svg.appendChild(chartSvgNode(doc,'rect',{x,y,width:Math.max(2,barW-5),height:h,rx:5,fill:chartPaletteColor(style,s,emphasis),opacity:emphasis?1:.9}));if(data.options.showValues)chartAddText(doc,svg,value,x+(barW-5)/2,y+(value>=0?-14:h+14),style,{size:17})});if(data.options.showLabels)chartAddText(doc,svg,label,box.x+i*step+step/2,box.y+box.h+30,style,{size:18,opacity:.82})})}
export function chartRenderLineArea(doc,svg,data,style,box,area=false){const all=data.series.flatMap(item=>item.values),range=chartRangeOf(all,data.options);chartGrid(doc,svg,box,style,data.options,range);const count=Math.max(1,data.categories.length),xOf=i=>box.x+(count===1?box.w/2:box.w*i/(count-1)),yOf=v=>box.y+box.h*(range.max-v)/range.span;data.series.forEach((series,s)=>{const points=series.values.map((v,i)=>[xOf(i),yOf(v)]);if(!points.length)return;const color=chartPaletteColor(style,s);if(area){const zero=chartClamp(yOf(0),box.y,box.y+box.h),d=`M ${points[0][0]} ${zero} L ${points.map(p=>`${p[0]} ${p[1]}`).join(' L ')} L ${points.at(-1)[0]} ${zero} Z`;svg.appendChild(chartSvgNode(doc,'path',{d,fill:color,opacity:.18}))}svg.appendChild(chartSvgNode(doc,'polyline',{points:points.map(p=>p.join(',')).join(' '),fill:'none',stroke:color,'stroke-width':4,'stroke-linecap':'round','stroke-linejoin':'round'}));points.forEach((p,i)=>{const emphasis=i===data.options.emphasisIndex;svg.appendChild(chartSvgNode(doc,'circle',{cx:p[0],cy:p[1],r:emphasis?7:5,fill:emphasis?style.emphasis:color,stroke:style.background==='transparent'?'#fff':style.background,'stroke-width':2}));if(data.options.showValues)chartAddText(doc,svg,series.values[i],p[0],p[1]-18,style,{size:17})})});if(data.options.showLabels)data.categories.forEach((label,i)=>chartAddText(doc,svg,label,xOf(i),box.y+box.h+30,style,{size:18,opacity:.82}))}
