export const DIAGRAM_SUBTYPES=Object.freeze(['matrix','pyramid','cycle','funnel','roadmap','swot','pest','porter']);
export const TABLE_ALIGNMENTS=Object.freeze(['left','center','right']);
const DiagramSubtypeSet=new Set(DIAGRAM_SUBTYPES),TableAlignmentSet=new Set(TABLE_ALIGNMENTS);
const structuredFinite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const structuredClamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const structuredClean=value=>value===undefined||value===null?'':String(value).trim();
const structuredArray=value=>Array.isArray(value)?value:[];
const structuredPlain=value=>{if(!value||typeof value!=='object'||Array.isArray(value)||value.nodeType!==undefined)return false;const proto=Object.getPrototypeOf(value);return proto===Object.prototype||proto===null};
function structuredJsonSafe(value,seen=new Set()){if(value===null||['string','boolean'].includes(typeof value))return true;if(typeof value==='number')return Number.isFinite(value);if(['undefined','function','symbol','bigint'].includes(typeof value))return false;if(typeof value!=='object'||value.nodeType!==undefined||seen.has(value))return false;seen.add(value);const children=Array.isArray(value)?value:Object.values(value),ok=children.every(child=>structuredJsonSafe(child,seen));seen.delete(value);return ok}
const structuredAlign=value=>TableAlignmentSet.has(value)?value:'left';
function structuredPartialStyle(input={},keys=[]){const source=structuredPlain(input)?input:{},out={};for(const key of keys){const value=source[key];if(value===undefined||value===null)continue;if(Array.isArray(value))out[key]=value.map(structuredClean).filter(Boolean);else if(typeof value==='number')out[key]=Number.isFinite(value)?value:undefined;else if(typeof value==='boolean')out[key]=value;else out[key]=structuredClean(value)}return Object.fromEntries(Object.entries(out).filter(([,value])=>value!==undefined))}
export function normalizeTableStyle(input={}){const custom=structuredPartialStyle(input,['variant','background','headerBackground','headerText','text','muted','borderColor','accent','fontFamily','headerFontWeight','bodyFontWeight','fontSize','headerFontSize','borderWidth','rowDividerWidth','cellPadding','radius']);return {variant:custom.variant||'clean',background:custom.background||'#ffffff',headerBackground:custom.headerBackground||'#eef2ff',headerText:custom.headerText||'#172033',text:custom.text||'#172033',muted:custom.muted||'#667085',borderColor:custom.borderColor||'#d9deea',accent:custom.accent||'#5b6cff',fontFamily:custom.fontFamily||'Inter, sans-serif',headerFontWeight:structuredFinite(custom.headerFontWeight,750),bodyFontWeight:structuredFinite(custom.bodyFontWeight,500),fontSize:structuredClamp(structuredFinite(custom.fontSize,24),10,72),headerFontSize:structuredClamp(structuredFinite(custom.headerFontSize,23),10,72),borderWidth:structuredClamp(structuredFinite(custom.borderWidth,1),0,8),rowDividerWidth:structuredClamp(structuredFinite(custom.rowDividerWidth,1),0,8),cellPadding:structuredClamp(structuredFinite(custom.cellPadding,18),0,60),radius:structuredClamp(structuredFinite(custom.radius,18),0,80)} }
export function resolveTableThemeStyle(theme={},overrides={}){const t=theme||{},mode=t.tableStyle?.header||'accent',dividers=t.tableStyle?.rowDividers||'subtle',variant=t.tableStyle?.variant||'clean',base={variant,background:t.surface||'#fff',headerBackground:mode==='solid'?(t.accent||'#5b6cff'):mode==='rule'?'transparent':(t.surface2||'#eef2ff'),headerText:mode==='solid'?(t.bg||'#fff'):(t.text||'#172033'),text:t.text||'#172033',muted:t.muted||'#667085',borderColor:t.line||'#d9deea',accent:t.accent||'#5b6cff',fontFamily:t.typography?.fontFamily||'Inter, sans-serif',headerFontWeight:t.typography?.titleWeight||800,bodyFontWeight:t.typography?.bodyWeight||500,fontSize:variant==='consulting'?22:24,headerFontSize:variant==='academic'?22:23,borderWidth:mode==='rule'?0:1,rowDividerWidth:dividers==='visible'?1.5:.65,cellPadding:variant==='tech'?15:18,radius:t.radius?.panel??18};return normalizeTableStyle({...base,...structuredPartialStyle(overrides,Object.keys(base))})}
function structuredNormalizeTableCell(input,fallbackAlign='left'){const source=structuredPlain(input)?input:{text:input};return {text:structuredClean(source.text??source.value),align:TableAlignmentSet.has(source.align)?source.align:fallbackAlign,background:structuredClean(source.background),color:structuredClean(source.color),fontWeight:source.fontWeight===undefined||source.fontWeight===null?null:structuredClamp(structuredFinite(source.fontWeight,500),100,1000)}}
function structuredNormalizeColumn(input,index,widthOverride){const source=structuredPlain(input)?input:{label:input},width=structuredFinite(widthOverride??source.width,0);return {id:structuredClean(source.id)||`col-${index+1}`,label:structuredClean(source.label??source.title),width:width>0?width:1,align:structuredAlign(source.align)}}
function structuredNormalizeRow(input,index,heightOverride,columnAlignments=[]){const source=Array.isArray(input)?{cells:input}:structuredPlain(input)?input:{cells:[input]},height=structuredFinite(heightOverride??source.height,0);return {id:structuredClean(source.id)||`row-${index+1}`,height:height>0?height:null,cells:structuredArray(source.cells).map((cell,cellIndex)=>structuredNormalizeTableCell(cell,columnAlignments[cellIndex]||'left'))}}
export function normalizeTableData(input={}){const source=structuredPlain(input)?input:{},rawHeader=Array.isArray(source.header)?{cells:source.header}:structuredPlain(source.header)?source.header:{},rawRows=structuredArray(source.rows),rawColumns=structuredArray(source.columns),count=Math.max(1,rawColumns.length,structuredArray(rawHeader.cells).length,...rawRows.map(row=>Array.isArray(row)?row.length:structuredArray(row?.cells).length));const widths=structuredArray(source.columnWidths),columns=Array.from({length:count},(_,index)=>structuredNormalizeColumn(rawColumns[index]??{},index,widths[index])),columnAlignments=columns.map(column=>column.align),headerCells=Array.from({length:count},(_,index)=>structuredNormalizeTableCell(structuredArray(rawHeader.cells)[index]??columns[index]?.label??'',columnAlignments[index]));const rows=rawRows.map((row,index)=>structuredNormalizeRow(row,index,structuredArray(source.rowHeights)[index],columnAlignments)).map(row=>({...row,cells:Array.from({length:count},(_,index)=>row.cells[index]||structuredNormalizeTableCell('',columnAlignments[index]))}));return {columns,header:{visible:source.header===false?false:rawHeader.visible!==false,height:structuredFinite(rawHeader.height,0)>0?structuredFinite(rawHeader.height,0):null,cells:headerCells},rows,style:structuredPartialStyle(source.style,['variant','background','headerBackground','headerText','text','muted','borderColor','accent','fontFamily','headerFontWeight','bodyFontWeight','fontSize','headerFontSize','borderWidth','rowDividerWidth','cellPadding','radius'])}}
export function validateTableData(input){const errors=[],warnings=[];if(!structuredPlain(input))errors.push({code:'TABLE_TYPE',path:'table',message:'table must be an object'});if(!structuredJsonSafe(input))errors.push({code:'TABLE_JSON_SAFE',path:'table',message:'table data must be pure finite JSON'});if(input?.columns!==undefined&&!Array.isArray(input.columns))errors.push({code:'TABLE_COLUMNS',path:'columns',message:'columns must be an array'});if(input?.rows!==undefined&&!Array.isArray(input.rows))errors.push({code:'TABLE_ROWS',path:'rows',message:'rows must be an array'});const normalized=normalizeTableData(input);if(!normalized.rows.length)warnings.push({code:'TABLE_EMPTY',path:'rows',message:'table has no body rows'});return {ok:errors.length===0,errors,warnings,normalized}}
export function normalizeTableElement(element={}){const normalized=normalizeTableData(element);element.columns=normalized.columns;element.header=normalized.header;element.rows=normalized.rows;element.style=normalized.style;return element}
export function validateTableElement(element={}){const check=validateTableData(element),errors=[...check.errors],warnings=[...check.warnings];if(element.type!=='table')errors.push({code:'TABLE_ELEMENT_TYPE',path:'type',message:'element.type must be table'});for(const key of ['x','y','w','h'])if(!Number.isFinite(Number(element[key])))errors.push({code:'TABLE_GEOMETRY',path:key,message:`${key} must be finite`});if(Number(element.w)<=0||Number(element.h)<=0)errors.push({code:'TABLE_GEOMETRY',path:'w/h',message:'table width/height must be positive'});return {ok:errors.length===0,errors,warnings,normalized:check.normalized}}

export function normalizeDiagramStyle(input={}){const custom=structuredPartialStyle(input,['variant','background','nodeFill','nodeText','nodeBorder','connectorColor','accent','accent2','muted','fontFamily','fontSize','detailFontSize','borderWidth','connectorWidth','radius','palette']);return {variant:custom.variant||'clean',background:custom.background||'transparent',nodeFill:custom.nodeFill||'#ffffff',nodeText:custom.nodeText||'#172033',nodeBorder:custom.nodeBorder||'#d9deea',connectorColor:custom.connectorColor||'#aab3c2',accent:custom.accent||'#5b6cff',accent2:custom.accent2||'#00a8a8',muted:custom.muted||'#667085',fontFamily:custom.fontFamily||'Inter, sans-serif',fontSize:structuredClamp(structuredFinite(custom.fontSize,26),10,72),detailFontSize:structuredClamp(structuredFinite(custom.detailFontSize,18),9,54),borderWidth:structuredClamp(structuredFinite(custom.borderWidth,1.5),0,8),connectorWidth:structuredClamp(structuredFinite(custom.connectorWidth,3),.5,12),radius:structuredClamp(structuredFinite(custom.radius,22),0,80),palette:structuredArray(custom.palette).length?structuredArray(custom.palette):[custom.accent||'#5b6cff',custom.accent2||'#00a8a8','#0e9f6e','#d1495b','#8a4fff','#d5a84d']} }
export function resolveDiagramThemeStyle(theme={},overrides={}){const t=theme||{},preset=t.diagramStyle||{},node=preset.node||'card',connector=preset.connector||'soft',variant=preset.variant||'clean',base={variant,background:'transparent',nodeFill:node==='outline'?'transparent':node==='panel'?(t.surface2||'#eef2ff'):(t.surface||'#fff'),nodeText:t.text||'#172033',nodeBorder:node==='outline'?(t.accent||'#5b6cff'):(t.line||'#d9deea'),connectorColor:connector==='angular'?(t.accent2||t.accent||'#00a8a8'):(t.line||'#aab3c2'),accent:t.accent||'#5b6cff',accent2:t.accent2||'#00a8a8',muted:t.muted||'#667085',fontFamily:t.typography?.fontFamily||'Inter, sans-serif',fontSize:variant==='consulting'?24:26,detailFontSize:variant==='academic'?17:18,borderWidth:node==='outline'?2:1.5,connectorWidth:connector==='straight'?2:connector==='angular'?3.5:3,radius:node==='box'?6:node==='outline'?4:(t.radius?.card??22),palette:[t.accent||'#5b6cff',t.accent2||'#00a8a8',t.success||'#0e9f6e',t.danger||'#d1495b',t.surface2||'#eef2ff',t.muted||'#667085']};return normalizeDiagramStyle({...base,...structuredPartialStyle(overrides,Object.keys(base))})}
function structuredNormalizeDiagramItem(input,index){const source=structuredPlain(input)?input:{label:input};return {id:structuredClean(source.id)||`item-${index+1}`,label:structuredClean(source.label??source.title??source.text),detail:structuredClean(source.detail??source.description),value:structuredClean(source.value),group:structuredClean(source.group),level:Math.max(0,Math.round(structuredFinite(source.level,index)))}}
export function normalizeDiagramData(input={}){const source=structuredPlain(input)?input:{},dataSource=structuredPlain(source.data)?source.data:source,subtype=DiagramSubtypeSet.has(source.subtype)?source.subtype:'matrix',rawItems=structuredArray(dataSource.items??source.items),layoutSource=structuredPlain(source.layout)?source.layout:{};return {subtype,data:{title:structuredClean(dataSource.title),centerLabel:structuredClean(dataSource.centerLabel),items:rawItems.map(structuredNormalizeDiagramItem)},layout:{direction:layoutSource.direction==='vertical'?'vertical':'horizontal',gap:structuredClamp(structuredFinite(layoutSource.gap,24),0,100),columns:Math.max(1,Math.min(6,Math.round(structuredFinite(layoutSource.columns,2))))},style:structuredPartialStyle(source.style,['variant','background','nodeFill','nodeText','nodeBorder','connectorColor','accent','accent2','muted','fontFamily','fontSize','detailFontSize','borderWidth','connectorWidth','radius','palette'])}}
export function validateDiagramData(input){const errors=[],warnings=[];if(!structuredPlain(input))errors.push({code:'DIAGRAM_TYPE',path:'diagram',message:'diagram must be an object'});if(!structuredJsonSafe(input))errors.push({code:'DIAGRAM_JSON_SAFE',path:'diagram',message:'diagram data must be pure finite JSON'});if(input?.subtype!==undefined&&!DiagramSubtypeSet.has(input.subtype))errors.push({code:'DIAGRAM_SUBTYPE',path:'subtype',message:`unsupported diagram subtype: ${input.subtype}`});const normalized=normalizeDiagramData(input);if(!normalized.data.items.length)warnings.push({code:'DIAGRAM_EMPTY',path:'data.items',message:'diagram has no items'});const recommended={swot:4,pest:4,porter:5};if(recommended[normalized.subtype]&&normalized.data.items.length<recommended[normalized.subtype])warnings.push({code:'DIAGRAM_PRESET_ITEMS',path:'data.items',message:`${normalized.subtype} works best with ${recommended[normalized.subtype]} items`});return {ok:errors.length===0,errors,warnings,normalized}}
export function normalizeDiagramElement(element={}){const normalized=normalizeDiagramData(element);element.subtype=normalized.subtype;element.data=normalized.data;element.layout=normalized.layout;element.style=normalized.style;delete element.items;return element}
export function validateDiagramElement(element={}){const check=validateDiagramData(element),errors=[...check.errors],warnings=[...check.warnings];if(element.type!=='diagram')errors.push({code:'DIAGRAM_ELEMENT_TYPE',path:'type',message:'element.type must be diagram'});for(const key of ['x','y','w','h'])if(!Number.isFinite(Number(element[key])))errors.push({code:'DIAGRAM_GEOMETRY',path:key,message:`${key} must be finite`});if(Number(element.w)<=0||Number(element.h)<=0)errors.push({code:'DIAGRAM_GEOMETRY',path:'w/h',message:'diagram width/height must be positive'});return {ok:errors.length===0,errors,warnings,normalized:check.normalized}}
