import { Core } from './runtime.js';
export const SCHEMA_VERSION = 1;
export const RUNTIME_VERSION = Core.VERSION;
export const normalizeProject = Core.Project.normalize;
export const normalizeVideo = Core.Project.normalizeVideo;
export const normalizeLayerRanges = Core.Project.normalizeLayerRanges;
export const createDefaultMaster = Core.Project.createDefaultMaster;
export const createNode = Core.Project.createNode;
export const cloneProject = Core.Project.clone;
export const projectForExport = Core.ExportData.project;
