import { Project, Tree } from '../model.js';
import { composerHashString } from './base.js';
import { normalizeSlideContent, normalizeDeckSpec, validateDeckSpec } from './schema.js';
import { TemplateRegistry, ThemeRegistry } from './templates.js';
import { Provenance } from './provenance.js';
import { Quality } from './quality.js';
import { resolveNativeChartLayout } from './chart-layout.js';
import { normalizeChartData, validateChartData, resolveChartThemeStyle, validateChartElement } from '../chart-data.js';

const chartNormalizeSlideContentBase=normalizeSlideContent,chartNormalizeDeckSpecBase=normalizeDeckSpec,chartValidateDeckSpecBase=validateDeckSpec,chartBaseQuality=Quality;
const chartRole=role=>role==='metrics'||role==='trend';
const rawChart=content=>content&&typeof content==='object'&&!Array.isArray(content)?content.chart:null;
const chartPointCount=chart=>Math.max(chart?.categories?.length||0,chart?.labels?.length||0,chart?.values?.length||0,chart?.series?.[0]?.values?.length||0);
const chartSuggestedRole=chart=>['line','area','waterfall'].includes(chart?.chartType)&&chartPointCount(chart)>=3?'trend':'metrics';
function chartProblem(code,path,message){return {code,path,message}}
function chartSampleIndices(count,limit=4){if(count<=0)return [];if(count<=limit)return Array.from({length:count},(_,index)=>index);const out=[];for(let index=0;index<limit;index++)out.push(Math.round(index*(count-1)/Math.max(1,limit-1)));return [...new Set(out)]}
function chartMatcherItems(input){
  const chart=normalizeChartData(input),labels=chart.labels.length?chart.labels:chart.categories,primary=chart.values.length?chart.values:(chart.series[0]?.values||[]),indices=chartSampleIndices(labels.length,4);
  return indices.map((sourceIndex,index)=>({
    id:`chart-item-${index+1}`,
    label:labels[sourceIndex]||`Item ${sourceIndex+1}`,
    value:primary[sourceIndex]===undefined?'':String(primary[sourceIndex]),
    detail:chart.series.length>1?chart.series.slice(1).map(series=>`${series.name} ${series.values[sourceIndex]??''}`.trim()).filter(Boolean).join(' · '):'',
    unit:'',image:''
  }));
}
function chartApplyMatcherFacts(content,input){if(!content?.items?.length)content.items=chartMatcherItems(input);return content}
function validatedChart(input,path='chart'){
  const check=validateChartData(input);
  if(!check.ok){const err=new Error(check.errors.map(item=>`${path}.${item.path}: ${item.message}`).join('; '));err.code='CHART_VALIDATION_ERROR';err.report=check;throw err}
  return check.normalized;
}
function templateManifest(template){if(typeof template==='string')return TemplateRegistry.get(template);if(template?.templateId)return TemplateRegistry.get(template.templateId);return template?.id?template:null}
function chartElement({chart,theme,title='',baseElements=[],template=null,intent={}}={}){
  const normalized=validatedChart(chart),themeTokens=ThemeRegistry.resolve(theme),style=resolveChartThemeStyle(themeTokens),maxZ=Math.max(999,...baseElements.map(item=>Number(item.z)||0)),manifest=templateManifest(template),layout=resolveNativeChartLayout({elements:baseElements,template:manifest,intent});
  return {id:`chart_${composerHashString(`${title}:${normalized.chartType}:${JSON.stringify(normalized)}`)}`,type:'chart',...layout.geometry,z:maxZ+1,...normalized,style,chartLayout:layout.meta,animation:{type:'inherit',delay:.08,duration:.55}};
}
export function normalizeSlideContentWithCharts(input={}){const normalized=chartNormalizeSlideContentBase(input),chart=rawChart(input);if(chart){normalized.chart=normalizeChartData(chart);chartApplyMatcherFacts(normalized,normalized.chart)}return normalized}
export function normalizeDeckSpecWithCharts(input={},options={}){const normalized=chartNormalizeDeckSpecBase(input,options),sourceSlides=Array.isArray(input?.slides)?input.slides:[];normalized.slides.forEach((slide,index)=>{const sourceSlide=sourceSlides[index]||{},chart=rawChart(sourceSlide.content);if(!chart)return;slide.content.chart=normalizeChartData(chart);chartApplyMatcherFacts(slide.content,slide.content.chart);if(sourceSlide.role===undefined||sourceSlide.role===null||sourceSlide.role==='')slide.role=chartSuggestedRole(slide.content.chart)});return normalized}
export function validateDeckSpecWithCharts(input){const base=chartValidateDeckSpecBase(input),errors=[...(base.errors||[])],warnings=[...(base.warnings||[])];for(const [index,slide] of (Array.isArray(input?.slides)?input.slides:[]).entries()){const chart=rawChart(slide?.content);if(!chart)continue;const check=validateChartData(chart);for(const item of check.errors)errors.push({...item,path:`slides[${index}].content.${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`slides[${index}].content.${item.path}`});if(slide?.role!==undefined&&!chartRole(slide.role))errors.push({code:'CHART_ROLE_UNSUPPORTED',path:`slides[${index}].role`,message:'native chart slides must use metrics or trend role, or omit role for automatic inference'})}return {ok:errors.length===0,errors,warnings}}
export function applyNativeChartToCompiled(result,request={}){const chart=rawChart(request.content),manifest=templateManifest(request.template),role=request.role||manifest?.roles?.find(chartRole)||null;if(!chart||!chartRole(role))return result;const source=result.elements||[],keep=source.filter(element=>(Number(element.y)||0)<280),native=chartElement({chart,theme:request.theme,title:request.content?.title,baseElements:source,template:manifest,intent:request.intent||{}});return {...result,elements:[...keep,native],generatedElementIds:[...keep.map(element=>element.id),native.id],chartType:native.chartType}}
export function compileSlideWithCharts(baseCompileSlide,request={}){const validation=rawChart(request.content)?validateChartData(request.content.chart):null;if(validation&&!validation.ok){const err=new Error(validation.errors.map(item=>item.message).join('; '));err.code='CHART_VALIDATION_ERROR';err.report=validation;throw err}return applyNativeChartToCompiled(baseCompileSlide(request),request)}
function attachNodeChart(node,chart,theme,options={}){if(!node||!chart||!chartRole(node.composer?.role||node.deckRole))return node;const source=node.slideElements||[],keep=source.filter(element=>(Number(element.y)||0)<280),native=chartElement({chart,theme,title:node.composer?.content?.title||node.title,baseElements:source,template:options.template||options.templateId||node.composer?.selectedTemplateId,intent:options.intent||node.composer?.designIntent||{}});node.slideElements=[...keep,native];node.composer ||= {};node.composer.content={...(node.composer.content||{}),chart:normalizeChartData(chart)};Provenance.attach(node,node.composer,node.slideElements);return node}
function chartMap(project){const map=new Map();Tree.walkAll(project,node=>{const chart=node.composer?.content?.chart;if(chart)map.set(node.id,chart)});return map}
export function compileDeckWithCharts(baseCompileDeck,spec,options={}){const validation=validateDeckSpecWithCharts(spec);if(!validation.ok){const err=new Error(validation.errors.map(item=>`${item.path}: ${item.message}`).join('; '));err.code='SPEC_VALIDATION_ERROR';err.report=validation;throw err}const result=baseCompileDeck(spec,options),slides=Array.isArray(spec?.slides)?spec.slides:[];(result.project.children||[]).forEach((node,index)=>{const chart=rawChart(slides[index]?.content);if(chart)attachNodeChart(node,chart,node.deckTheme||options.theme||spec.theme,{templateId:node.composer?.selectedTemplateId,intent:node.composer?.designIntent||{}})});Project.normalize(result.project,{schemaVersion:1});result.quality=NativeChartQuality.validateProject(result.project);return result}
export function applyTemplateWithCharts(baseApply,request={}){const chart=request.node?.composer?.content?.chart||rawChart(request.content),result=baseApply(request),target=result.node||request.node;if(chart)attachNodeChart(target,chart,request.theme||target?.deckTheme,{template:request.template,templateId:request.templateId,intent:request.intent||target?.composer?.designIntent||{}});return {...result,node:target,elements:target?.slideElements||result.elements,metadata:target?.composer||result.metadata}}
export function relayoutNodeWithCharts(baseRelayout,node,options={}){const chart=node?.composer?.content?.chart,result=baseRelayout(node,options),target=result||node;if(chart)attachNodeChart(target,chart,options.theme||node.deckTheme,{...options,templateId:options.templateId||target?.composer?.selectedTemplateId,intent:options.intent||target?.composer?.designIntent||{}});return result}
export function rethemeProjectWithCharts(baseRetheme,project,theme,options={}){const charts=chartMap(project),result=baseRetheme(project,theme,options);Tree.walkAll(result,node=>{const chart=charts.get(node.id);if(chart)attachNodeChart(node,chart,theme,{templateId:node.composer?.selectedTemplateId,intent:node.composer?.designIntent||{}})});Project.normalize(result,{schemaVersion:1});return result}
function chartOnlyReport(elements=[],options={}){const errors=[],warnings=[],ids=new Set(),types={};for(const [index,element] of elements.entries()){types[element?.type]=(types[element?.type]||0)+1;if(!element?.id)errors.push(chartProblem('ELEMENT_ID_MISSING',`elements[${index}]`,'元素缺少 id'));else if(ids.has(element.id))errors.push(chartProblem('ELEMENT_ID_DUPLICATE',`elements[${index}]`,`重复元素 id：${element.id}`));else ids.add(element.id);if(element?.type==='chart'){const check=validateChartElement(element);for(const item of check.errors)errors.push({...item,path:`elements[${index}].${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`elements[${index}].${item.path}`});const width=options.width??1600,height=options.height??900;if(Number(element.x)<0||Number(element.y)<0||Number(element.x)+Number(element.w)>width||Number(element.y)+Number(element.h)>height)errors.push(chartProblem('GEOMETRY_OUT_OF_BOUNDS',`elements[${index}]`,'元素超出 1600×900 画布'))}}return {ok:errors.length===0,errors,warnings,metrics:{elements:elements.length,types}}}
function validateElementsWithCharts(elements=[],options={}){const nonCharts=elements.filter(item=>item?.type!=='chart'),base=chartBaseQuality.validateElements(nonCharts,options),chartReport=chartOnlyReport(elements,options),errors=[...base.errors],warnings=[...base.warnings];for(const item of chartReport.errors)if(item.code.startsWith('CHART_')||item.code==='GEOMETRY_OUT_OF_BOUNDS'||(item.code==='ELEMENT_ID_DUPLICATE'&&!base.errors.some(baseItem=>baseItem.code==='ELEMENT_ID_DUPLICATE'&&baseItem.message===item.message)))errors.push(item);warnings.push(...chartReport.warnings);return {ok:errors.length===0,errors,warnings,metrics:{elements:elements.length,types:chartReport.metrics.types}}}
function validateProjectWithCharts(project){const clone=Project.clone(project);Tree.walkAll(clone,node=>{node.slideElements=(node.slideElements||[]).map(element=>element.type==='chart'?{id:element.id,type:'shape',shape:'rect',x:element.x,y:element.y,w:element.w,h:element.h,z:element.z,fill:'transparent',borderColor:'transparent',borderWidth:0,radius:0,animation:element.animation}:element)});const base=chartBaseQuality.validateProject(clone),errors=[...base.errors],warnings=[...base.warnings];Tree.walkAll(project,node=>{for(const [index,element] of (node.slideElements||[]).entries()){if(element.type!=='chart')continue;const check=validateChartElement(element);for(const item of check.errors)errors.push({...item,path:`node.${node.id}.elements[${index}].${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`node.${node.id}.elements[${index}].${item.path}`})}});return {ok:errors.length===0,errors,warnings,metrics:base.metrics}}
export const NativeChartQuality=Object.freeze({...chartBaseQuality,validateElements:validateElementsWithCharts,validateProject:validateProjectWithCharts});
