const RICH_TYPES=new Set(['table','diagram']);
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const area=e=>Math.max(0,num(e?.w))*Math.max(0,num(e?.h));
const body=e=>e&&num(e.y)>=270&&num(e.w)>60&&num(e.h)>40;
const rich=e=>RICH_TYPES.has(e?.type);
function boundsOf(elements=[]){if(!elements.length)return null;const left=Math.min(...elements.map(e=>num(e.x))),top=Math.min(...elements.map(e=>num(e.y))),right=Math.max(...elements.map(e=>num(e.x)+num(e.w))),bottom=Math.max(...elements.map(e=>num(e.y)+num(e.h)));return {x:left,y:top,w:right-left,h:bottom-top}}
function overlapRatio(a,b){const x1=Math.max(num(a.x),num(b.x)),y1=Math.max(num(a.y),num(b.y)),x2=Math.min(num(a.x)+num(a.w),num(b.x)+num(b.w)),y2=Math.min(num(a.y)+num(a.h),num(b.y)+num(b.h));if(x2<=x1||y2<=y1)return 0;return (x2-x1)*(y2-y1)/Math.max(1,area(a))}
function usableBody(elements=[]){return elements.filter(body).filter(e=>!rich(e))}
function chooseSlot(referenceElements=[],params={},intent={}){const candidates=usableBody(referenceElements),union=boundsOf(candidates);if(!union)return {bounds:{x:112,y:300,w:1280,h:450},keep:referenceElements.filter(e=>num(e.y)<270)};const shapes=candidates.filter(e=>e.type==='shape'&&area(e)>=70000).sort((a,b)=>area(b)-area(a));const visualPref=intent.contentBalance==='visual'||num(params.visualWeight,1)>1.08||num(intent.visualWeight,1)>1.08;const splitCandidates=shapes.filter(e=>area(e)<=area(union)*.72&&num(e.w)>=360&&num(e.h)>=180);let slot=null;if(splitCandidates.length&&!visualPref){const direction=params.direction||intent.direction||'horizontal';slot=splitCandidates.slice().sort((a,b)=>direction==='vertical'?num(a.y)-num(b.y):num(b.x)-num(a.x))[0]}if(!slot)slot={...union};const pad=slot.type==='shape'?14:0,bounds={x:Math.round(num(slot.x)+pad),y:Math.round(num(slot.y)+pad),w:Math.round(Math.max(120,num(slot.w)-pad*2)),h:Math.round(Math.max(100,num(slot.h)-pad*2))};const keep=referenceElements.filter(e=>{if(num(e.y)<270)return true;if(e===slot)return true;return overlapRatio(e,bounds)<.28});return {bounds,keep}}
export function reflowRichElements(currentElements=[],referenceElements=[],options={}){const current=currentElements||[],richElement=current.find(rich);if(!richElement)return current;const slot=chooseSlot(referenceElements,options.params||{},options.intent||{}),headerFallback=current.filter(e=>!rich(e)&&num(e.y)<270),referenceKeep=slot.keep?.length?slot.keep:headerFallback,maxZ=Math.max(999,...referenceKeep.map(e=>num(e.z))),nextRich={...richElement,...slot.bounds,z:maxZ+1};return [...referenceKeep.filter(e=>!rich(e)),nextRich]}
export function reflowRichNode(node,referenceElements=[],options={}){if(!node?.slideElements?.some(rich))return node;node.slideElements=reflowRichElements(node.slideElements,referenceElements,{params:options.params||node.composer?.selectedParams||node.composer?.intentResolution?.params||{},intent:options.intent||node.composer?.designIntent||{}});return node}
export const RichLayout=Object.freeze({types:Object.freeze([...RICH_TYPES]),reflowElements:reflowRichElements,reflowNode:reflowRichNode});
