import { Project, Tree } from '../model.js';
import { composerHashString } from './base.js';
import { TemplateRegistry, ThemeRegistry } from './templates.js';
import { Provenance } from './provenance.js';
import { normalizeSlideContentWithCharts, normalizeDeckSpecWithCharts, validateDeckSpecWithCharts, compileSlideWithCharts, compileDeckWithCharts, applyTemplateWithCharts, relayoutNodeWithCharts, rethemeProjectWithCharts, NativeChartQuality } from './chart.js';
import { normalizeTableData, validateTableData, resolveTableThemeStyle, validateTableElement, normalizeDiagramData, validateDiagramData, resolveDiagramThemeStyle, validateDiagramElement } from '../structured-data.js';

const structuredRawTable=content=>content&&typeof content==='object'&&!Array.isArray(content)?content.table:null;
const structuredRawDiagram=content=>content&&typeof content==='object'&&!Array.isArray(content)?content.diagram:null;
const structuredExplicitRole=slide=>slide?.role!==undefined&&slide?.role!==null&&slide?.role!=='';
function structuredSuggestedRole(kind,input){
  if(kind==='table')return 'table';
  const subtype=normalizeDiagramData(input).subtype;
  if(subtype==='roadmap')return 'roadmap';
  if(['cycle','funnel'].includes(subtype))return 'process';
  if(subtype==='pyramid')return 'cards';
  return 'matrix';
}
function structuredSample(values=[],limit=6){if(values.length<=limit)return values.map((value,index)=>({value,index}));const out=[];for(let slot=0;slot<limit;slot++){const index=Math.round(slot*(values.length-1)/Math.max(1,limit-1));if(!out.some(item=>item.index===index))out.push({value:values[index],index})}return out}
function structuredMatcherItems(kind,input){
  if(kind==='table'){
    const data=normalizeTableData(input),sample=structuredSample(data.rows,6),items=sample.map(({value:row,index})=>({id:row.id||`table-row-${index+1}`,label:row.cells[0]?.text||`Row ${index+1}`,value:row.cells[1]?.text||'',detail:row.cells.slice(2).map(cell=>cell.text).filter(Boolean).join(' · '),unit:'',image:''}));
    if(items.length===1)items.push({id:'table-row-summary',label:'数据行',value:'1',detail:'单行表格',unit:'',image:''});
    return items;
  }
  const data=normalizeDiagramData(input),sample=structuredSample(data.data.items,6);
  return sample.map(({value:item,index})=>({id:item.id||`diagram-item-${index+1}`,label:item.label||`Item ${index+1}`,value:item.value||'',detail:item.detail||'',unit:'',image:''}));
}
function structuredApplyMatcherFacts(content,kind,input){if(!content?.items?.length)content.items=structuredMatcherItems(kind,input);return content}
function structuredRichKinds(content={}){return [['chart',content?.chart],['table',structuredRawTable(content)],['diagram',structuredRawDiagram(content)]].filter(([,value])=>value!==undefined&&value!==null)}
function structuredValidatedTable(input,path='table'){const check=validateTableData(input);if(!check.ok){const err=new Error(check.errors.map(item=>`${path}.${item.path}: ${item.message}`).join('; '));err.code='TABLE_VALIDATION_ERROR';err.report=check;throw err}return check.normalized}
function structuredValidatedDiagram(input,path='diagram'){const check=validateDiagramData(input);if(!check.ok){const err=new Error(check.errors.map(item=>`${path}.${item.path}: ${item.message}`).join('; '));err.code='DIAGRAM_VALIDATION_ERROR';err.report=check;throw err}return check.normalized}
function structuredValidateRichConflict(content,path='content'){const kinds=structuredRichKinds(content);if(kinds.length<=1)return null;return {code:'RICH_BODY_CONFLICT',path,message:`only one rich body is allowed: ${kinds.map(([kind])=>kind).join(', ')}`}}
function structuredTemplateManifest(template){if(typeof template==='string')return TemplateRegistry.get(template);if(template?.templateId)return TemplateRegistry.get(template.templateId);return template?.id?template:null}
function structuredBodyElement({kind,input,theme,title='',baseElements=[]}={}){const themeTokens=ThemeRegistry.resolve(theme),maxZ=Math.max(999,...baseElements.map(item=>Number(item.z)||0));if(kind==='table'){const normalized=structuredValidatedTable(input),style=resolveTableThemeStyle(themeTokens,normalized.style);return {id:`table_${composerHashString(`${title}:${JSON.stringify(normalized)}`)}`,type:'table',x:112,y:292,w:1280,h:470,z:maxZ+1,...normalized,style,animation:{type:'inherit',delay:.08,duration:.55}}}const normalized=structuredValidatedDiagram(input),style=resolveDiagramThemeStyle(themeTokens,normalized.style);return {id:`diagram_${composerHashString(`${title}:${normalized.subtype}:${JSON.stringify(normalized)}`)}`,type:'diagram',x:112,y:292,w:1280,h:470,z:maxZ+1,...normalized,style,animation:{type:'inherit',delay:.08,duration:.55}}}
export function normalizeSlideContentWithStructured(input={}){const normalized=normalizeSlideContentWithCharts(input),table=structuredRawTable(input),diagram=structuredRawDiagram(input);if(table){normalized.table=normalizeTableData(table);structuredApplyMatcherFacts(normalized,'table',table)}if(diagram){normalized.diagram=normalizeDiagramData(diagram);structuredApplyMatcherFacts(normalized,'diagram',diagram)}return normalized}
export function normalizeDeckSpecWithStructured(input={},options={}){const normalized=normalizeDeckSpecWithCharts(input,options),sourceSlides=Array.isArray(input?.slides)?input.slides:[];normalized.slides.forEach((slide,index)=>{const sourceSlide=sourceSlides[index]||{},content=sourceSlide.content,table=structuredRawTable(content),diagram=structuredRawDiagram(content);if(table){slide.content.table=normalizeTableData(table);structuredApplyMatcherFacts(slide.content,'table',table);if(!structuredExplicitRole(sourceSlide))slide.role=structuredSuggestedRole('table',table)}if(diagram){slide.content.diagram=normalizeDiagramData(diagram);structuredApplyMatcherFacts(slide.content,'diagram',diagram);if(!structuredExplicitRole(sourceSlide))slide.role=structuredSuggestedRole('diagram',diagram)}});return normalized}
export function validateDeckSpecWithStructured(input){const base=validateDeckSpecWithCharts(input),errors=[...(base.errors||[])],warnings=[...(base.warnings||[])];for(const [index,slide] of (Array.isArray(input?.slides)?input.slides:[]).entries()){const content=slide?.content||{},conflict=structuredValidateRichConflict(content,`slides[${index}].content`);if(conflict)errors.push(conflict);if(structuredRawTable(content)){const check=validateTableData(content.table);for(const item of check.errors)errors.push({...item,path:`slides[${index}].content.table.${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`slides[${index}].content.table.${item.path}`})}if(structuredRawDiagram(content)){const check=validateDiagramData(content.diagram);for(const item of check.errors)errors.push({...item,path:`slides[${index}].content.diagram.${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`slides[${index}].content.diagram.${item.path}`})}}return {ok:errors.length===0,errors,warnings}}
export function applyStructuredToCompiled(result,request={}){const content=request.content||{},table=structuredRawTable(content),diagram=structuredRawDiagram(content),conflict=structuredValidateRichConflict(content);if(conflict){const err=new Error(conflict.message);err.code=conflict.code;err.report={ok:false,errors:[conflict],warnings:[]};throw err}if(!table&&!diagram)return result;const keep=(result.elements||[]).filter(element=>(Number(element.y)||0)<280),kind=table?'table':'diagram',native=structuredBodyElement({kind,input:table||diagram,theme:request.theme,title:content.title,baseElements:keep}),manifest=structuredTemplateManifest(request.template);return {...result,elements:[...keep,native],generatedElementIds:[...keep.map(element=>element.id),native.id],structuredType:kind,diagramSubtype:kind==='diagram'?native.subtype:undefined,templateId:result.templateId||manifest?.id}}
export function compileSlideWithStructured(baseCompileSlide,request={}){const conflict=structuredValidateRichConflict(request.content||{});if(conflict){const err=new Error(conflict.message);err.code=conflict.code;err.report={ok:false,errors:[conflict],warnings:[]};throw err}if(structuredRawTable(request.content)){const check=validateTableData(request.content.table);if(!check.ok){const err=new Error(check.errors.map(item=>item.message).join('; '));err.code='TABLE_VALIDATION_ERROR';err.report=check;throw err}}if(structuredRawDiagram(request.content)){const check=validateDiagramData(request.content.diagram);if(!check.ok){const err=new Error(check.errors.map(item=>item.message).join('; '));err.code='DIAGRAM_VALIDATION_ERROR';err.report=check;throw err}}return applyStructuredToCompiled(compileSlideWithCharts(baseCompileSlide,request),request)}
function structuredAttachNode(node,kind,input,theme){if(!node||!input)return node;const keep=(node.slideElements||[]).filter(element=>(Number(element.y)||0)<280),native=structuredBodyElement({kind,input,theme,title:node.composer?.content?.title||node.title,baseElements:keep});node.slideElements=[...keep,native];node.composer ||= {};node.composer.content={...(node.composer.content||{}),[kind]:kind==='table'?normalizeTableData(input):normalizeDiagramData(input)};delete node.composer.content[kind==='table'?'diagram':'table'];delete node.composer.content.chart;Provenance.attach(node,node.composer,node.slideElements);return node}
function structuredContentMap(project){const map=new Map();Tree.walkAll(project,node=>{const table=node.composer?.content?.table,diagram=node.composer?.content?.diagram;if(table)map.set(node.id,{kind:'table',input:table});else if(diagram)map.set(node.id,{kind:'diagram',input:diagram})});return map}
export function compileDeckWithStructured(baseCompileDeck,spec,options={}){const validation=validateDeckSpecWithStructured(spec);if(!validation.ok){const err=new Error(validation.errors.map(item=>`${item.path}: ${item.message}`).join('; '));err.code='SPEC_VALIDATION_ERROR';err.report=validation;throw err}const prepared=normalizeDeckSpecWithStructured(spec,options),result=compileDeckWithCharts(baseCompileDeck,prepared,options),slides=prepared.slides||[];(result.project.children||[]).forEach((node,index)=>{const content=slides[index]?.content||{},table=structuredRawTable(content),diagram=structuredRawDiagram(content);if(table)structuredAttachNode(node,'table',table,node.deckTheme||options.theme||prepared.theme);else if(diagram)structuredAttachNode(node,'diagram',diagram,node.deckTheme||options.theme||prepared.theme)});Project.normalize(result.project,{schemaVersion:1});result.quality=StructuredQuality.validateProject(result.project);return result}
export function applyTemplateWithStructured(baseApply,request={}){const requestedContent=request.content||request.node?.composer?.content||{},conflict=structuredValidateRichConflict(requestedContent);if(conflict){const err=new Error(conflict.message);err.code=conflict.code;err.report={ok:false,errors:[conflict],warnings:[]};throw err}const table=structuredRawTable(requestedContent),diagram=structuredRawDiagram(requestedContent),chart=requestedContent?.chart,chained=applyTemplateWithCharts(baseApply,request),target=chained.node||request.node;if(table)structuredAttachNode(target,'table',table,request.theme||target?.deckTheme);else if(diagram)structuredAttachNode(target,'diagram',diagram,request.theme||target?.deckTheme);else if(chart&&target?.composer?.content){delete target.composer.content.table;delete target.composer.content.diagram}return {...chained,node:target,elements:target?.slideElements||chained.elements,metadata:target?.composer||chained.metadata}}
export function relayoutNodeWithStructured(baseRelayout,node,options={}){const content=node?.composer?.content||{},table=structuredRawTable(content),diagram=structuredRawDiagram(content),result=relayoutNodeWithCharts(baseRelayout,node,options),target=result||node;if(table)structuredAttachNode(target,'table',table,options.theme||target.deckTheme);else if(diagram)structuredAttachNode(target,'diagram',diagram,options.theme||target.deckTheme);return target}
export function rethemeProjectWithStructured(baseRetheme,project,theme,options={}){const structured=structuredContentMap(project),result=rethemeProjectWithCharts(baseRetheme,project,theme,options);Tree.walkAll(result,node=>{const item=structured.get(node.id);if(item)structuredAttachNode(node,item.kind,item.input,theme)});Project.normalize(result,{schemaVersion:1});return result}
function structuredProxyElement(element){return ['table','diagram'].includes(element?.type)?{id:element.id,type:'shape',shape:'rect',x:element.x,y:element.y,w:element.w,h:element.h,z:element.z,fill:'transparent',borderColor:'transparent',borderWidth:0,radius:0,animation:element.animation}:element}
function validateElementsWithStructured(elements=[],options={}){const base=NativeChartQuality.validateElements(elements.map(structuredProxyElement),options),errors=[...base.errors],warnings=[...base.warnings],types={};for(const [index,element] of elements.entries()){types[element?.type]=(types[element?.type]||0)+1;if(element?.type!=='table'&&element?.type!=='diagram')continue;const check=element.type==='table'?validateTableElement(element):validateDiagramElement(element);for(const item of check.errors)errors.push({...item,path:`elements[${index}].${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`elements[${index}].${item.path}`});const width=options.width??1600,height=options.height??900;if(Number(element.x)<0||Number(element.y)<0||Number(element.x)+Number(element.w)>width||Number(element.y)+Number(element.h)>height)errors.push({code:'GEOMETRY_OUT_OF_BOUNDS',path:`elements[${index}]`,message:'元素超出 1600×900 画布'})}return {ok:errors.length===0,errors,warnings,metrics:{...base.metrics,elements:elements.length,types}}}
function validateProjectWithStructured(project){const clone=Project.clone(project);Tree.walkAll(clone,node=>{node.slideElements=(node.slideElements||[]).map(structuredProxyElement)});const base=NativeChartQuality.validateProject(clone),errors=[...base.errors],warnings=[...base.warnings];Tree.walkAll(project,node=>{for(const [index,element] of (node.slideElements||[]).entries()){if(element.type!=='table'&&element.type!=='diagram')continue;const check=element.type==='table'?validateTableElement(element):validateDiagramElement(element);for(const item of check.errors)errors.push({...item,path:`node.${node.id}.elements[${index}].${item.path}`});for(const item of check.warnings||[])warnings.push({...item,path:`node.${node.id}.elements[${index}].${item.path}`})}});return {ok:errors.length===0,errors,warnings,metrics:base.metrics}}
export const StructuredQuality=Object.freeze({...NativeChartQuality,validateElements:validateElementsWithStructured,validateProject:validateProjectWithStructured});
