import { DECK_THEMES, PAGE_ROLES, ComposerRoleSet, composerClean, composerThemeOf } from './base.js';
import { normalizeThemeManifest } from './themes.js';
import { contentFacts, normalizeSlideContent } from './schema.js';
const ComposerSlotSources=new Set(['title','subtitle','summary','takeaway','items','media']);
function composerCap(title=64,summary=180,items=[0,6],numeric=[0,6],media=[0,2]){return {titleChars:{max:title},summaryChars:{max:summary},items:{min:items[0],max:items[1]},numericItems:{min:numeric[0],max:numeric[1]},media:{min:media[0],max:media[1]}}}
function composerSlots(...sources){return sources.map((source,index)=>({id:`${source}-${index+1}`,kind:['items','media'].includes(source)?'collection':'text',source,required:source==='title'}))}
function composerTemplate(id,label,family,roles,capacity,variant,priority=50,slots=['title','summary','items','media']){return {id,label,family,roles,priority,capacity,slots:composerSlots(...slots),layout:{kind:family,variant,canvas:{width:1600,height:900}}}}
export const ComposerTemplateManifests=Object.freeze([
composerTemplate('cover-focus-01','聚焦封面','cover-focus',['cover'],composerCap(72,150,[0,5],[0,5],[0,1]),'focus',90,['title','subtitle','summary','items']),composerTemplate('cover-grid-01','章节封面','cover-grid',['cover'],composerCap(64,130,[1,6],[0,6],[0,1]),'grid',82,['title','subtitle','items']),composerTemplate('section-index-01','章节序号','section-index',['section'],composerCap(52,140,[0,4]),'index',85),composerTemplate('section-band-01','章节横幅','section-band',['section','cover'],composerCap(58,150,[0,6]),'band',76),composerTemplate('statement-panel-01','重点面板','statement-panel',['statement','quote','conclusion'],composerCap(60,180,[0,2]),'panel',84),composerTemplate('statement-split-01','观点分栏','statement-split',['statement','section','image','conclusion'],composerCap(54,170,[0,4],[0,4],[0,1]),'split',78),composerTemplate('cards-grid-01','卡片矩阵','cards-grid',['cards'],composerCap(50,100,[2,6]),'grid',86),composerTemplate('cards-list-01','纵向卡片','cards-list',['cards','compare'],composerCap(54,120,[2,6]),'list',78),composerTemplate('compare-split-01','左右对比','compare-split',['compare'],composerCap(50,100,[2,4]),'split',88),composerTemplate('compare-table-01','条目对照','compare-table',['compare','cards'],composerCap(52,120,[2,6]),'table',76),composerTemplate('process-line-01','横向流程','process-line',['process','timeline'],composerCap(52,100,[3,5]),'line',88),composerTemplate('process-steps-01','阶梯流程','process-steps',['process','cards'],composerCap(54,120,[3,6]),'steps',79),composerTemplate('metrics-cards-01','指标卡组','metrics-cards',['metrics'],composerCap(50,90,[2,4],[2,4]),'cards',90),composerTemplate('metrics-hero-01','核心指标','metrics-hero',['metrics','statement'],composerCap(50,110,[1,4],[1,4]),'hero',84),composerTemplate('trend-bars-01','趋势柱列','trend-bars',['trend','metrics'],composerCap(52,90,[3,6],[2,6]),'bars',88),composerTemplate('trend-steps-01','趋势阶梯','trend-steps',['trend','timeline'],composerCap(54,110,[3,6],[1,6]),'steps',79),composerTemplate('timeline-line-01','水平时间轴','timeline-line',['timeline','process','trend'],composerCap(52,100,[3,5]),'line',87),composerTemplate('timeline-vertical-01','垂直时间轴','timeline-vertical',['timeline'],composerCap(54,120,[3,6]),'vertical',80),composerTemplate('quote-center-01','中心引用','quote-center',['quote'],composerCap(48,200,[0,1]),'center',88,['title','summary','takeaway']),composerTemplate('quote-side-01','侧栏引用','quote-side',['quote','statement'],composerCap(52,190,[0,2]),'side',80,['title','summary','takeaway']),composerTemplate('image-left-01','左图右文','image-left',['image'],composerCap(52,150,[0,3],[0,3],[0,2]),'left',88),composerTemplate('image-right-01','右图左文','image-right',['image','statement'],composerCap(52,150,[0,3],[0,3],[0,2]),'right',81),composerTemplate('conclusion-actions-01','行动结论','conclusion-actions',['conclusion'],composerCap(52,160,[1,4]),'actions',90),composerTemplate('conclusion-summary-01','总结收束','conclusion-summary',['conclusion','statement'],composerCap(54,180,[0,4]),'summary',82)
].map(item=>Object.freeze(item)));
export function validateComposerTemplate(template){const errors=[];if(!template||typeof template!=='object')return {ok:false,errors:['template must be an object']};if(!composerClean(template.id))errors.push('template id required');if(!composerClean(template.family))errors.push('template family required');if(!Array.isArray(template.roles)||!template.roles.length||template.roles.some(role=>!ComposerRoleSet.has(role)))errors.push('template roles invalid');if(!template.capacity||typeof template.capacity!=='object')errors.push('template capacity required');for(const [key,range] of Object.entries(template.capacity||{}))if(range&&typeof range==='object'&&range.min!==undefined&&range.max!==undefined&&Number(range.min)>Number(range.max))errors.push(`capacity ${key} min exceeds max`);if(!Array.isArray(template.slots)||template.slots.some(slot=>!ComposerSlotSources.has(slot.source)))errors.push('template slot source invalid');return {ok:errors.length===0,errors}}
export function createComposerTemplateRegistry(initial=[]){const map=new Map(),api={register(template){const check=validateComposerTemplate(template);if(!check.ok)throw new Error(check.errors.join('; '));if(map.has(template.id))throw new Error(`duplicate template id: ${template.id}`);map.set(template.id,Object.freeze({...template}));return api},get(id){return map.get(id)||null},has(id){return map.has(id)},list(filter={}){return [...map.values()].filter(item=>(!filter.role||item.roles.includes(filter.role))&&(!filter.family||item.family===filter.family))},validate:validateComposerTemplate};initial.forEach(item=>api.register(item));return api}
export const TemplateRegistry=createComposerTemplateRegistry(ComposerTemplateManifests);
export const ThemeRegistry=Object.freeze({get(id){return composerThemeOf(id)},has(id){return DECK_THEMES.some(theme=>theme.id===id)},list(){return DECK_THEMES.slice()},normalize(input,fallback='aurora'){return normalizeThemeManifest(input,fallback)},resolve(input,fallback='aurora'){return normalizeThemeManifest(input,fallback)}});
function composerRangeCheck(value,rule,label,reasons){if(!rule)return true;if(rule.min!==undefined&&value<rule.min){reasons.push(`${label} ${value} < ${rule.min}`);return false}if(rule.max!==undefined&&value>rule.max){reasons.push(`${label} ${value} > ${rule.max}`);return false}return true}
export function capacityFits(content,capacity={}){const facts=contentFacts(content),reasons=[];let ok=true;ok=composerRangeCheck(facts.titleChars,capacity.titleChars,'titleChars',reasons)&&ok;ok=composerRangeCheck(facts.summaryChars,capacity.summaryChars,'summaryChars',reasons)&&ok;ok=composerRangeCheck(facts.itemCount,capacity.items,'items',reasons)&&ok;ok=composerRangeCheck(facts.numericItemCount,capacity.numericItems,'numericItems',reasons)&&ok;ok=composerRangeCheck(facts.mediaCount,capacity.media,'media',reasons)&&ok;return {ok,reasons,facts}}
export const Capacity=Object.freeze({facts:contentFacts,fits:capacityFits});
export function requiredSlotsAvailable(content,template){const value=normalizeSlideContent(content),missing=[];for(const slot of template.slots||[]){if(!slot.required)continue;const source=value[slot.source];if(Array.isArray(source)?source.length===0:!source)missing.push(slot.source)}return {ok:missing.length===0,missing}}
export const ComposerRoleCatalog=Object.freeze(PAGE_ROLES.slice());
