const DEFAULT_PALETTE=Object.freeze({bg:'#F7F8FC',surface:'#FFFFFF',surface2:'#EEF2FF',text:'#172033',muted:'#667085',accent:'#5B6CFF',accent2:'#00A8A8',line:'#D9DEEA',danger:'#D1495B',success:'#0E9F6E'});
const PALETTES=Object.freeze({
  aurora:{label:'晨光',...DEFAULT_PALETTE},
  cobalt:{label:'深海蓝',bg:'#081426',surface:'#10233E',surface2:'#153052',text:'#F3F7FF',muted:'#A9B7CC',accent:'#4DA3FF',accent2:'#5DE0E6',line:'#29486D',danger:'#FF7B88',success:'#4ED7A8'},
  forest:{label:'森林',bg:'#F5F8F4',surface:'#FFFFFF',surface2:'#E7F0E8',text:'#183126',muted:'#687A70',accent:'#2F7D4A',accent2:'#7E9F35',line:'#D4E0D7',danger:'#B65050',success:'#2F7D4A'},
  ember:{label:'暖焰',bg:'#FFF8F1',surface:'#FFFFFF',surface2:'#FFF0E2',text:'#39251B',muted:'#7D6A60',accent:'#E66A35',accent2:'#D9A441',line:'#EAD8CA',danger:'#C94B4B',success:'#3C8C63'},
  plum:{label:'紫曜',bg:'#F8F5FB',surface:'#FFFFFF',surface2:'#F0E7F7',text:'#2E2037',muted:'#796C81',accent:'#8A4FFF',accent2:'#D65DB1',line:'#E3D7EA',danger:'#C84F69',success:'#4A9A78'},
  slate:{label:'岩灰',bg:'#F4F5F7',surface:'#FFFFFF',surface2:'#E9EBEF',text:'#20242B',muted:'#6B7280',accent:'#3C4657',accent2:'#7A8699',line:'#D7DAE0',danger:'#B84A55',success:'#34805A'},
  sand:{label:'沙金',bg:'#FBF7EF',surface:'#FFFDF8',surface2:'#F4EAD7',text:'#352D22',muted:'#756B5D',accent:'#A8782A',accent2:'#D5A84D',line:'#E5D9C3',danger:'#B35245',success:'#4F8060'},
  ink:{label:'墨黑',bg:'#0B0D10',surface:'#171A1F',surface2:'#22262D',text:'#F7F7F5',muted:'#A3A8B2',accent:'#F2C94C',accent2:'#7AD7F0',line:'#343A44',danger:'#FF7575',success:'#54D6A0'},
  ocean:{label:'海盐',bg:'#F3FAFC',surface:'#FFFFFF',surface2:'#E2F3F7',text:'#153039',muted:'#64808A',accent:'#157C8C',accent2:'#3AAED8',line:'#CCE4E9',danger:'#C24F63',success:'#2B8D71'},
  mint:{label:'薄荷',bg:'#F4FBF8',surface:'#FFFFFF',surface2:'#E1F5ED',text:'#17352A',muted:'#678176',accent:'#19A974',accent2:'#75C9A9',line:'#CCE8DC',danger:'#C64D5F',success:'#178F65'},
  rose:{label:'玫瑰',bg:'#FFF6F7',surface:'#FFFFFF',surface2:'#FCE7EA',text:'#3B252B',muted:'#826C72',accent:'#D65C7A',accent2:'#EE9B9B',line:'#EFD7DD',danger:'#B8455D',success:'#4B8A70'},
  mono:{label:'黑白',bg:'#FFFFFF',surface:'#FFFFFF',surface2:'#F3F3F3',text:'#111111',muted:'#686868',accent:'#111111',accent2:'#858585',line:'#D9D9D9',danger:'#8F2E2E',success:'#336B4A'}
});

export const THEME_V2_SCHEMA_VERSION=2;
export const THEME_V2_FALLBACK_ID='aurora';
export const ThemeV2Defaults=Object.freeze({
  typography:Object.freeze({fontFamily:'Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif',displayFontFamily:'Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif',monoFontFamily:'"SFMono-Regular", Consolas, "Liberation Mono", monospace',bodyScale:1,titleScale:1,bodyWeight:500,titleWeight:820,lineHeight:1.18,letterSpacing:0}),
  spacing:Object.freeze({rhythm:1,contentScale:1}),
  radius:Object.freeze({card:28,panel:34,image:30,accent:6}),
  border:Object.freeze({width:1,cardWidth:1,imageWidth:1,style:'solid'}),
  shadow:Object.freeze({card:'none',image:'none',accent:'none'}),
  titleTreatment:Object.freeze({scale:1,weight:820,letterSpacing:0}),
  subtitleTreatment:Object.freeze({scale:1,weight:500,opacity:1}),
  numberTreatment:Object.freeze({scale:1,weight:900,fontFamily:'"SFMono-Regular", Consolas, "Liberation Mono", monospace',letterSpacing:-0.4,colorMode:'inherit'}),
  cardTreatment:Object.freeze({radius:28,borderWidth:1,shadow:'none',surfaceMode:'surface'}),
  imageTreatment:Object.freeze({radius:30,borderWidth:1,fit:'cover',shadow:'none'}),
  decoration:Object.freeze({accentRadius:6,accentOpacity:1,lineScale:1,kickerTracking:1.1}),
  chartStyle:Object.freeze({variant:'clean',grid:'subtle',labels:'compact'}),
  diagramStyle:Object.freeze({variant:'clean',connector:'soft',node:'card'}),
  tableStyle:Object.freeze({variant:'clean',header:'accent',rowDividers:'subtle'})
});

export const ThemeVisualProfiles=Object.freeze({
  aurora:{kind:'light-modern',typography:{bodyScale:1,titleScale:1,bodyWeight:500,titleWeight:820,lineHeight:1.18},spacing:{rhythm:1},radius:{card:28,panel:34,image:30,accent:6},border:{cardWidth:1,imageWidth:1},shadow:{card:'0 10px 28px rgba(23,32,51,.08)',image:'0 12px 34px rgba(23,32,51,.10)'},titleTreatment:{scale:1,weight:820,letterSpacing:-0.5},subtitleTreatment:{scale:1,weight:500,opacity:.92},numberTreatment:{scale:1.04,weight:900,colorMode:'accent'},cardTreatment:{radius:28,borderWidth:1,shadow:'0 10px 28px rgba(23,32,51,.08)'},imageTreatment:{radius:30,borderWidth:1,fit:'cover',shadow:'0 12px 34px rgba(23,32,51,.10)'},decoration:{accentRadius:6,accentOpacity:1,lineScale:1,kickerTracking:1.1}},
  cobalt:{kind:'dark-tech',typography:{fontFamily:'Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif',displayFontFamily:'Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif',bodyScale:.98,titleScale:1.04,bodyWeight:520,titleWeight:860,lineHeight:1.12,letterSpacing:.1},spacing:{rhythm:.94},radius:{card:16,panel:20,image:18,accent:2},border:{cardWidth:1.4,imageWidth:1.4},shadow:{card:'0 18px 46px rgba(0,0,0,.28)',image:'0 22px 54px rgba(0,0,0,.34)'},titleTreatment:{scale:1.05,weight:880,letterSpacing:-1.1},subtitleTreatment:{scale:.96,weight:520,opacity:.86},numberTreatment:{scale:1.12,weight:950,colorMode:'accent'},cardTreatment:{radius:16,borderWidth:1.4,shadow:'0 18px 46px rgba(0,0,0,.28)'},imageTreatment:{radius:18,borderWidth:1.4,fit:'cover',shadow:'0 22px 54px rgba(0,0,0,.34)'},decoration:{accentRadius:2,accentOpacity:.92,lineScale:.8,kickerTracking:1.5},chartStyle:{variant:'tech',grid:'visible',labels:'mono'},diagramStyle:{variant:'tech',connector:'angular',node:'panel'},tableStyle:{variant:'tech',header:'solid',rowDividers:'visible'}},
  forest:{kind:'organic-professional',typography:{bodyScale:1,titleScale:1,bodyWeight:520,titleWeight:800,lineHeight:1.22},spacing:{rhythm:1.05},radius:{card:24,panel:30,image:34,accent:9},border:{cardWidth:1,imageWidth:1},shadow:{card:'0 8px 22px rgba(24,49,38,.07)',image:'0 12px 28px rgba(24,49,38,.10)'},titleTreatment:{scale:1,weight:800,letterSpacing:-.2},subtitleTreatment:{scale:1.02,weight:500,opacity:.9},numberTreatment:{scale:1.02,weight:850,colorMode:'accent'},cardTreatment:{radius:24,borderWidth:1,shadow:'0 8px 22px rgba(24,49,38,.07)'},imageTreatment:{radius:34,borderWidth:1,fit:'cover',shadow:'0 12px 28px rgba(24,49,38,.10)'},decoration:{accentRadius:9,accentOpacity:.92,lineScale:1.15,kickerTracking:1}},
  ember:{kind:'editorial-warm',typography:{fontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',displayFontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',bodyScale:1.02,titleScale:1.05,bodyWeight:500,titleWeight:760,lineHeight:1.28},spacing:{rhythm:1.08},radius:{card:12,panel:18,image:10,accent:1},border:{cardWidth:1,imageWidth:0},shadow:{card:'0 6px 18px rgba(57,37,27,.06)',image:'none'},titleTreatment:{scale:1.06,weight:760,letterSpacing:-.3},subtitleTreatment:{scale:1.02,weight:500,opacity:.9},numberTreatment:{scale:1.08,weight:800,fontFamily:'Georgia, "Noto Serif SC", serif',colorMode:'accent'},cardTreatment:{radius:12,borderWidth:1,shadow:'0 6px 18px rgba(57,37,27,.06)'},imageTreatment:{radius:10,borderWidth:0,fit:'cover',shadow:'none'},decoration:{accentRadius:1,accentOpacity:1,lineScale:.65,kickerTracking:1.35}},
  plum:{kind:'editorial-visual',typography:{bodyScale:1,titleScale:1.04,bodyWeight:500,titleWeight:850,lineHeight:1.2},spacing:{rhythm:1.02},radius:{card:36,panel:42,image:40,accent:12},border:{cardWidth:0,imageWidth:0},shadow:{card:'0 18px 38px rgba(46,32,55,.12)',image:'0 20px 44px rgba(46,32,55,.14)'},titleTreatment:{scale:1.04,weight:850,letterSpacing:-.8},subtitleTreatment:{scale:1,weight:500,opacity:.88},numberTreatment:{scale:1.12,weight:950,colorMode:'accent'},cardTreatment:{radius:36,borderWidth:0,shadow:'0 18px 38px rgba(46,32,55,.12)'},imageTreatment:{radius:40,borderWidth:0,fit:'cover',shadow:'0 20px 44px rgba(46,32,55,.14)'},decoration:{accentRadius:12,accentOpacity:.88,lineScale:1.4,kickerTracking:1.2}},
  slate:{kind:'consulting-business',typography:{fontFamily:'Arial, "Noto Sans SC", "Microsoft YaHei", sans-serif',displayFontFamily:'Arial, "Noto Sans SC", "Microsoft YaHei", sans-serif',bodyScale:.97,titleScale:.96,bodyWeight:500,titleWeight:760,lineHeight:1.16},spacing:{rhythm:.94},radius:{card:8,panel:10,image:8,accent:0},border:{cardWidth:1.3,imageWidth:1},shadow:{card:'none',image:'none'},titleTreatment:{scale:.96,weight:760,letterSpacing:-.2},subtitleTreatment:{scale:.94,weight:500,opacity:.92},numberTreatment:{scale:1,weight:850,colorMode:'text'},cardTreatment:{radius:8,borderWidth:1.3,shadow:'none'},imageTreatment:{radius:8,borderWidth:1,fit:'contain',shadow:'none'},decoration:{accentRadius:0,accentOpacity:1,lineScale:.7,kickerTracking:1.6},chartStyle:{variant:'consulting',grid:'visible',labels:'dense'},diagramStyle:{variant:'consulting',connector:'straight',node:'box'},tableStyle:{variant:'consulting',header:'rule',rowDividers:'visible'}},
  sand:{kind:'academic-formal',typography:{fontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',displayFontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',bodyScale:.98,titleScale:.98,bodyWeight:500,titleWeight:720,lineHeight:1.3},spacing:{rhythm:1.1},radius:{card:4,panel:6,image:2,accent:0},border:{cardWidth:1,imageWidth:1.5},shadow:{card:'none',image:'none'},titleTreatment:{scale:.98,weight:720,letterSpacing:.1},subtitleTreatment:{scale:1,weight:500,opacity:.88},numberTreatment:{scale:1,weight:760,fontFamily:'Georgia, "Noto Serif SC", serif',colorMode:'text'},cardTreatment:{radius:4,borderWidth:1,shadow:'none'},imageTreatment:{radius:2,borderWidth:1.5,fit:'contain',shadow:'none'},decoration:{accentRadius:0,accentOpacity:.9,lineScale:.55,kickerTracking:1.8},chartStyle:{variant:'academic',grid:'visible',labels:'formal'},diagramStyle:{variant:'academic',connector:'straight',node:'outline'},tableStyle:{variant:'academic',header:'rule',rowDividers:'visible'}},
  ink:{kind:'dark-editorial',typography:{fontFamily:'Georgia, "Noto Serif SC", serif',displayFontFamily:'Georgia, "Noto Serif SC", serif',bodyScale:1.01,titleScale:1.08,bodyWeight:500,titleWeight:760,lineHeight:1.24},spacing:{rhythm:1.04},radius:{card:2,panel:4,image:2,accent:0},border:{cardWidth:1,imageWidth:0},shadow:{card:'none',image:'none'},titleTreatment:{scale:1.08,weight:760,letterSpacing:-.6},subtitleTreatment:{scale:1,weight:500,opacity:.84},numberTreatment:{scale:1.14,weight:800,fontFamily:'Georgia, serif',colorMode:'accent'},cardTreatment:{radius:2,borderWidth:1,shadow:'none'},imageTreatment:{radius:2,borderWidth:0,fit:'cover',shadow:'none'},decoration:{accentRadius:0,accentOpacity:1,lineScale:.5,kickerTracking:1.9}},
  ocean:{kind:'light-modern',typography:{bodyScale:1,titleScale:1.01,bodyWeight:500,titleWeight:810,lineHeight:1.2},spacing:{rhythm:1.02},radius:{card:30,panel:36,image:28,accent:8},border:{cardWidth:1,imageWidth:1},shadow:{card:'0 10px 28px rgba(21,48,57,.07)',image:'0 12px 30px rgba(21,48,57,.09)'},titleTreatment:{scale:1.01,weight:810,letterSpacing:-.4},subtitleTreatment:{scale:1,weight:500,opacity:.9},numberTreatment:{scale:1.06,weight:900,colorMode:'accent'},cardTreatment:{radius:30,borderWidth:1,shadow:'0 10px 28px rgba(21,48,57,.07)'},imageTreatment:{radius:28,borderWidth:1,fit:'cover',shadow:'0 12px 30px rgba(21,48,57,.09)'},decoration:{accentRadius:8,accentOpacity:.94,lineScale:1.15,kickerTracking:1.1}},
  mint:{kind:'clean-friendly',typography:{bodyScale:1,titleScale:.99,bodyWeight:500,titleWeight:790,lineHeight:1.22},spacing:{rhythm:1.04},radius:{card:32,panel:36,image:36,accent:12},border:{cardWidth:.8,imageWidth:.8},shadow:{card:'0 8px 24px rgba(23,53,42,.06)',image:'0 10px 28px rgba(23,53,42,.08)'},titleTreatment:{scale:.99,weight:790,letterSpacing:-.2},subtitleTreatment:{scale:1.02,weight:500,opacity:.9},numberTreatment:{scale:1.04,weight:880,colorMode:'accent'},cardTreatment:{radius:32,borderWidth:.8,shadow:'0 8px 24px rgba(23,53,42,.06)'},imageTreatment:{radius:36,borderWidth:.8,fit:'cover',shadow:'0 10px 28px rgba(23,53,42,.08)'},decoration:{accentRadius:12,accentOpacity:.9,lineScale:1.25,kickerTracking:1}},
  rose:{kind:'editorial-visual',typography:{fontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',displayFontFamily:'Georgia, "Noto Serif SC", "Songti SC", serif',bodyScale:1.02,titleScale:1.06,bodyWeight:500,titleWeight:780,lineHeight:1.26},spacing:{rhythm:1.08},radius:{card:24,panel:32,image:44,accent:10},border:{cardWidth:.8,imageWidth:0},shadow:{card:'0 14px 34px rgba(59,37,43,.09)',image:'0 18px 44px rgba(59,37,43,.12)'},titleTreatment:{scale:1.06,weight:780,letterSpacing:-.4},subtitleTreatment:{scale:1.03,weight:500,opacity:.9},numberTreatment:{scale:1.1,weight:820,fontFamily:'Georgia, serif',colorMode:'accent'},cardTreatment:{radius:24,borderWidth:.8,shadow:'0 14px 34px rgba(59,37,43,.09)'},imageTreatment:{radius:44,borderWidth:0,fit:'cover',shadow:'0 18px 44px rgba(59,37,43,.12)'},decoration:{accentRadius:10,accentOpacity:.86,lineScale:1.5,kickerTracking:1.25}},
  mono:{kind:'minimal-formal',typography:{fontFamily:'Arial, "Noto Sans SC", sans-serif',displayFontFamily:'Arial, "Noto Sans SC", sans-serif',bodyScale:.96,titleScale:.94,bodyWeight:500,titleWeight:720,lineHeight:1.18},spacing:{rhythm:.96},radius:{card:0,panel:0,image:0,accent:0},border:{cardWidth:1,imageWidth:1},shadow:{card:'none',image:'none'},titleTreatment:{scale:.94,weight:720,letterSpacing:.2},subtitleTreatment:{scale:.95,weight:500,opacity:.9},numberTreatment:{scale:.98,weight:780,colorMode:'text'},cardTreatment:{radius:0,borderWidth:1,shadow:'none'},imageTreatment:{radius:0,borderWidth:1,fit:'contain',shadow:'none'},decoration:{accentRadius:0,accentOpacity:1,lineScale:.45,kickerTracking:2},chartStyle:{variant:'mono',grid:'visible',labels:'dense'},diagramStyle:{variant:'mono',connector:'straight',node:'outline'},tableStyle:{variant:'mono',header:'rule',rowDividers:'visible'}}
});

function pureData(value){if(value===null||['string','number','boolean'].includes(typeof value))return value;if(Array.isArray(value))return value.map(pureData).filter(item=>item!==undefined);if(typeof value!=='object'||value.nodeType!==undefined)return undefined;const out={};for(const [key,child] of Object.entries(value)){const clean=pureData(child);if(clean!==undefined)out[key]=clean}return out}
function mergeData(base,override){const out={...base};for(const [key,value] of Object.entries(override||{})){if(value&&typeof value==='object'&&!Array.isArray(value)&&base?.[key]&&typeof base[key]==='object'&&!Array.isArray(base[key]))out[key]=mergeData(base[key],value);else out[key]=value}return out}
function freezeData(value){if(!value||typeof value!=='object'||Object.isFrozen(value))return value;for(const child of Object.values(value))freezeData(child);return Object.freeze(value)}
function manifestFrom(id,palette,profile={}){const colors={bg:palette.bg,surface:palette.surface,surface2:palette.surface2,text:palette.text,muted:palette.muted,accent:palette.accent,accent2:palette.accent2,line:palette.line,danger:palette.danger,success:palette.success};const visual=mergeData(ThemeV2Defaults,profile);return freezeData({schemaVersion:THEME_V2_SCHEMA_VERSION,id,label:palette.label,kind:profile.kind||'custom',...colors,colors,...visual})}

export const DECK_THEMES=Object.freeze(Object.entries(PALETTES).map(([id,palette])=>manifestFrom(id,palette,ThemeVisualProfiles[id])));
export const ComposerThemeMap=Object.freeze(Object.fromEntries(DECK_THEMES.map(theme=>[theme.id,theme])));

export function normalizeThemeManifest(input,fallback=THEME_V2_FALLBACK_ID){
  const fallbackTheme=ComposerThemeMap[fallback]||ComposerThemeMap[THEME_V2_FALLBACK_ID];
  if(typeof input==='string'||input==null)return ComposerThemeMap[input]||fallbackTheme;
  if(typeof input!=='object'||Array.isArray(input))return fallbackTheme;
  const clean=pureData(input)||{},base=ComposerThemeMap[clean.id]||fallbackTheme,knownId=ComposerThemeMap[clean.id]?clean.id:base.id;
  const palette={};for(const key of ['bg','surface','surface2','text','muted','accent','accent2','line','danger','success'])palette[key]=clean[key]??clean.colors?.[key]??base[key];
  const merged=mergeData(base,{...clean,...palette,colors:{...base.colors,...clean.colors,...palette},schemaVersion:THEME_V2_SCHEMA_VERSION,id:String(knownId),label:String(clean.label||base.label)});
  return freezeData(merged);
}
export function composerThemeOf(value){return normalizeThemeManifest(value,THEME_V2_FALLBACK_ID)}
